/**
 * Booking click tracker — lightweight localStorage-based analytics.
 * Counts real clicks on reservation buttons generated by Kompilot.
 *
 * Storage keys:
 *   kompilot_booking_clicks              → global total (all time)
 *   kompilot_booking_clicks_{pid}_{YYYY-MM}  → per platform, per month
 *   kompilot_booking_clicks_daily_{YYYY-MM-DD} → per day (last 30 days)
 */

const TOTAL_KEY = 'kompilot_booking_clicks';
const BASKET_KEY = (userId: string) => `kompilot_avg_basket_${userId}`;
const MONTHLY_KEY = (platformId: string, month: string) =>
  `kompilot_booking_clicks_${platformId}_${month}`;
const DAILY_KEY = (dateStr: string) =>
  `kompilot_booking_clicks_daily_${dateStr}`;

export const DEFAULT_AVG_BASKET = 40;

// ── Date helpers ──────────────────────────────────────────────────────────────

/** YYYY-MM */
export function getCurrentMonthKey(): string {
  const d = new Date();
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`;
}

/** YYYY-MM-DD */
export function getCurrentDayKey(): string {
  return formatDay(new Date());
}

/** Return a YYYY-MM-DD date string N days before today (negative N = future) */
export function daysAgoKey(n: number): string {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return formatDay(d);
}

/** Parse a YYYY-MM-DD string into a Date */
function parseDay(s: string): Date {
  const [y, m, d] = s.split('-').map(Number);
  return new Date(y, m - 1, d);
}

/** Format a Date as YYYY-MM-DD */
function formatDay(d: Date): string {
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;
}

// ── Core tracking ─────────────────────────────────────────────────────────────

/**
 * Increment the global + daily booking click counter.
 * Called automatically by trackBookingClickForPlatform.
 */
export function trackBookingClick(): void {
  try {
    // Global total
    const total = parseInt(localStorage.getItem(TOTAL_KEY) ?? '0', 10);
    localStorage.setItem(TOTAL_KEY, String(total + 1));

    // Daily total
    const day = getCurrentDayKey();
    const dayKey = DAILY_KEY(day);
    const dayCount = parseInt(localStorage.getItem(dayKey) ?? '0', 10);
    localStorage.setItem(dayKey, String(dayCount + 1));

    // Dispatch so live counters can update
    window.dispatchEvent(new CustomEvent('kompilot:booking-click'));
  } catch { /* noop */ }
}

/**
 * Track a click for a specific platform (monthly) AND increment globals.
 * This is the preferred call from booking buttons.
 */
export function trackBookingClickForPlatform(platformId: string): void {
  try {
    const month = getCurrentMonthKey();
    const key = MONTHLY_KEY(platformId, month);
    const current = parseInt(localStorage.getItem(key) ?? '0', 10);
    localStorage.setItem(key, String(current + 1));
    // Also increment global + daily
    trackBookingClick();
  } catch { /* noop */ }
}

// ── Read helpers ──────────────────────────────────────────────────────────────

/** Get the all-time total click count */
export function getBookingClicks(): number {
  try {
    return parseInt(localStorage.getItem(TOTAL_KEY) ?? '0', 10);
  } catch {
    return 0;
  }
}

/** Get clicks for a specific platform this month (or a given month) */
export function getMonthlyClicksForPlatform(platformId: string, month?: string): number {
  try {
    const m = month ?? getCurrentMonthKey();
    return parseInt(localStorage.getItem(MONTHLY_KEY(platformId, m)) ?? '0', 10);
  } catch {
    return 0;
  }
}

/** Get clicks for ALL platforms this month as a map platformId → count */
export function getAllPlatformClicksThisMonth(): Record<string, number> {
  try {
    const month = getCurrentMonthKey();
    const result: Record<string, number> = {};
    for (let i = 0; i < localStorage.length; i++) {
      const key = localStorage.key(i);
      if (key?.startsWith('kompilot_booking_clicks_') && key.endsWith(`_${month}`) && !key.includes('daily')) {
        const platformId = key
          .replace('kompilot_booking_clicks_', '')
          .replace(`_${month}`, '');
        result[platformId] = parseInt(localStorage.getItem(key) ?? '0', 10);
      }
    }
    return result;
  } catch {
    return {};
  }
}

/** Get total clicks for this month (all platforms combined from daily tracker) */
export function getMonthlyClicksTotal(): number {
  try {
    const now = new Date();
    const month = getCurrentMonthKey();
    let total = 0;
    for (let i = 0; i < localStorage.length; i++) {
      const key = localStorage.key(i);
      if (key?.startsWith('kompilot_booking_clicks_daily_') && key.includes(month.slice(0, 7))) {
        total += parseInt(localStorage.getItem(key) ?? '0', 10);
      }
    }
    return total;
  } catch {
    return 0;
  }
}

/** Get the last N days of click data (including days with 0) */
export function getDailyClicksHistory(days = 7): Array<{ date: string; label: string; clicks: number }> {
  const result: Array<{ date: string; label: string; clicks: number }> = [];
  const today = new Date();

  for (let i = days - 1; i >= 0; i--) {
    const d = new Date(today);
    d.setDate(today.getDate() - i);
    const dateStr = formatDay(d);
    const clicks = (() => {
      try {
        return parseInt(localStorage.getItem(DAILY_KEY(dateStr)) ?? '0', 10);
      } catch {
        return 0;
      }
    })();
    const label = i === 0 ? "Auj." : i === 1 ? "Hier" : `${d.getDate()}/${d.getMonth() + 1}`;
    result.push({ date: dateStr, label, clicks });
  }
  return result;
}

// ── Average basket ────────────────────────────────────────────────────────────

/** Get configured average basket for a user (defaults to 40€) */
export function getAverageBasket(userId?: string): number {
  if (!userId) return DEFAULT_AVG_BASKET;
  try {
    const v = localStorage.getItem(BASKET_KEY(userId));
    const parsed = v ? parseInt(v, 10) : DEFAULT_AVG_BASKET;
    return isNaN(parsed) || parsed <= 0 ? DEFAULT_AVG_BASKET : parsed;
  } catch {
    return DEFAULT_AVG_BASKET;
  }
}

/** Persist the average basket preference for a user */
export function setAverageBasket(userId: string, value: number): void {
  try {
    localStorage.setItem(BASKET_KEY(userId), String(Math.max(1, value)));
  } catch { /* noop */ }
}

// ── Estimations ───────────────────────────────────────────────────────────────

/** Calculate estimated reservations (15% of clicks) */
export function estimateReservations(clicks: number): number {
  return Math.round(clicks * 0.15);
}

/** Calculate estimated revenue */
export function estimateRevenue(reservations: number, avgBasket: number): number {
  return reservations * avgBasket;
}

// ── Date range queries ────────────────────────────────────────────────────────

/**
 * Get daily click data for an arbitrary date range [startDate, endDate] (inclusive).
 * Both dates should be YYYY-MM-DD strings.
 */
export function getClicksForDateRange(
  startDate: string,
  endDate: string
): Array<{ date: string; label: string; clicks: number }> {
  const result: Array<{ date: string; label: string; clicks: number }> = [];
  const start = new Date(startDate + 'T00:00:00');
  const end = new Date(endDate + 'T00:00:00');

  const cur = new Date(start);
  while (cur <= end) {
    const dateStr = formatDay(cur);
    const clicks = (() => {
      try {
        return parseInt(localStorage.getItem(DAILY_KEY(dateStr)) ?? '0', 10);
      } catch {
        return 0;
      }
    })();
    const d = cur.getDate();
    const m = cur.getMonth() + 1;
    const label = `${d}/${m}`;
    result.push({ date: dateStr, label, clicks });
    cur.setDate(cur.getDate() + 1);
  }
  return result;
}

/**
 * Sum all clicks within a date range.
 */
export function sumClicksForDateRange(startDate: string, endDate: string): number {
  return getClicksForDateRange(startDate, endDate).reduce((acc, d) => acc + d.clicks, 0);
}

// ── Dev helper ────────────────────────────────────────────────────────────────

/** Simulate N clicks for a given platform (for testing) */
export function simulateClicks(platformId: string, count = 1): void {
  for (let i = 0; i < count; i++) {
    trackBookingClickForPlatform(platformId);
  }
}
