import { Link } from '@tanstack/react-router';
import { ArrowRight, BarChart3, CalendarDays, CheckCircle2, FileText, Inbox, MapPin, Search, ShieldCheck, Sparkles, Star } from 'lucide-react';

const FEATURES = [
  { icon: Sparkles, title: 'Création de contenus avec l’IA', text: 'Préparez une publication adaptée à votre activité et à chaque canal.', detail: 'Partez d’un brief, relisez la proposition puis validez avant diffusion.', href: '/features', preview: ['Idée de contenu', 'Marché local : 3 angles à tester', 'Brouillon prêt à relire'] },
  { icon: CalendarDays, title: 'Calendrier éditorial', text: 'Visualisez les contenus, temps forts et actions à venir.', detail: 'Planifiez sans perdre le contexte ni les validations.', href: '/features', preview: ['Calendrier', 'Lun  ·  Avis client', 'Jeu  ·  Publication'] },
  { icon: Star, title: 'Gestion des avis Google', text: 'Centralisez les avis et préparez des réponses personnalisées.', detail: 'Priorisez les réponses sensibles et gardez la main sur chaque envoi.', href: '/local', preview: ['Avis à traiter', 'Votre réponse est en préparation', 'Validation requise'] },
  { icon: Inbox, title: 'Boîte de réception centralisée', text: 'Regroupez messages et retours issus de vos canaux connectés.', detail: 'Un espace unique pour répondre sans oublier une conversation.', href: '/features', preview: ['Boîte de réception', 'Instagram  ·  Nouveau message', 'Google  ·  À suivre'] },
  { icon: Search, title: 'Scanner SEO local et GEO', text: 'Analysez les signaux qui aident Google et les moteurs IA à comprendre votre activité.', detail: 'Transformez les écarts détectés en recommandations lisibles.', href: '/local', preview: ['Diagnostic de visibilité', 'Informations locales', 'Citations et contenus'] },
  { icon: BarChart3, title: 'Reporting et conversions', text: 'Suivez les actions et indicateurs utiles sans tableur dispersé.', detail: 'Partagez une lecture claire des progrès avec votre équipe ou vos clients.', href: '/features', preview: ['Rapport du mois', 'Actions réalisées', 'Prochaines priorités'] },
];

const SECTORS = [
  ['/secteurs/restaurants', 'Restaurants', 'Menus, avis, actualités et visibilité locale.'], ['/secteurs/boutiques', 'Boutiques et commerces', 'Produits, temps forts et trafic en magasin.'], ['/secteurs/beaute', 'Beauté et coiffure', 'Prestations, disponibilités et avis.'], ['/secteurs/sport', 'Sport et coaching', 'Cours, événements et inscriptions.'], ['/secteurs/artisans', 'Artisans', 'Zone d’intervention, réalisations et devis.'], ['/secteurs/sante', 'Santé et bien-être', 'Expertise locale et contenus validés.'], ['/secteurs/immobilier', 'Immobilier', 'Biens, expertise de quartier et contacts.'], ['/secteurs/agences', 'Agences marketing', 'Pilotage multi-clients et reporting.'],
] as const;

const STEPS = [['01', 'Connectez votre présence', 'Google Business Profile, votre site et les réseaux sociaux que vous utilisez déjà.'], ['02', 'Recevez votre plan d’action', 'Kompilot rassemble contenus, avis et signaux de visibilité pour prioriser les prochaines actions.'], ['03', 'Validez et mesurez', 'Vous gardez le contrôle avant chaque publication ou réponse, puis suivez l’activité dans le cockpit.']];

function ModulePreview({ lines }: { lines: string[] }) {
  return <div className="module-preview" aria-label="Aperçu du module Kompilot"><div className="module-preview-top"><span /><span /><span /></div><div className="module-preview-body"><p>{lines[0]}</p>{lines.slice(1).map((line, index) => <div key={line} className="module-preview-row"><i>{index + 1}</i><span>{line}</span><b>{index === lines.length - 2 ? 'À valider' : 'Prêt'}</b></div>)}</div></div>;
}

export function VisibilityLandingSections({ onCta }: { onCta: () => void }) {
  return <>
    <section id="benefices" className="landing-section landing-benefits"><div className="landing-container"><div className="landing-section-intro"><p className="nc-section-label">Les résultats au quotidien</p><h2>Moins de dispersion. Plus d’actions utiles.</h2><p>Kompilot rassemble les signaux importants de votre présence et vous aide à décider quoi faire ensuite.</p></div><div className="benefit-grid">{[['01', 'Gagnez du temps chaque semaine', 'Un cockpit unique pour préparer, valider et suivre vos actions.'], ['02', 'Ne laissez plus vos avis sans réponse', 'Une file claire pour traiter les retours importants au bon moment.'], ['03', 'Suivez votre visibilité sur Google et dans les IA', 'Des recommandations lisibles pour progresser sans promettre un résultat automatique.']].map(([num, title, text]) => <article key={num} className="benefit-card"><span>{num}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>

    <section id="probleme" className="landing-section landing-problem"><div className="landing-container problem-layout"><div className="landing-section-intro"><p className="nc-section-label">Le point de départ</p><h2>Votre visibilité est dispersée entre trop d’outils.</h2><p>Publications irrégulières, avis sans réponse, messages dispersés : Kompilot transforme ces signaux en actions claires, au même endroit.</p></div><div className="problem-list">{[['01', 'Publications irrégulières', 'Les idées existent, mais restent dans les notes ou arrivent trop tard.'], ['02', 'Avis sans réponse', 'Une réponse utile demande du contexte et un vrai suivi.'], ['03', 'Messages dispersés', 'Chaque canal ajoute une nouvelle boîte à surveiller.'], ['04', 'Visibilité IA inconnue', 'Vous ne savez pas toujours quelles informations les moteurs comprennent.']].map(([num, title, text]) => <article key={num}><span>{num}</span><div><h3>{title}</h3><p>{text}</p></div></article>)}</div></div></section>

    <section id="fonctionnalites" className="landing-section landing-features"><div className="landing-container"><div className="landing-section-intro"><p className="nc-section-label">Les modules du cockpit</p><h2>Tout ce qu’il faut pour piloter votre présence locale</h2><p>Chaque module répond à un problème concret et vous laisse la validation finale.</p></div><div className="feature-grid">{FEATURES.map(({ icon: Icon, title, text, detail, href, preview }) => <article key={title} className="feature-card"><div className="feature-card-icon"><Icon size={19} /></div><ModulePreview lines={preview} /><h3>{title}</h3><p>{text}</p><small>{detail}</small><Link to={href as '/'}>Voir le module <ArrowRight size={14} /></Link></article>)}</div></div></section>

    <section id="fonctionnement" className="landing-section landing-workflow"><div className="landing-container workflow-layout"><div className="landing-section-intro"><p className="nc-section-label">Le fonctionnement</p><h2>Connectez, priorisez, validez.</h2><p>Une mise en route simple, puis un rythme de travail qui reste sous votre contrôle.</p><div className="human-validation"><ShieldCheck size={17} /> Validation humaine avant publication</div></div><div className="workflow-list">{STEPS.map(([num, title, text]) => <article key={num}><span>{num}</span><div><h3>{title}</h3><p>{text}</p></div></article>)}</div></div></section>

    <section id="geo" className="landing-section landing-geo"><div className="landing-container geo-layout"><div><p className="nc-section-label">SEO local + GEO</p><h2>Votre entreprise apparaît-elle dans les réponses des IA&nbsp;?</h2><p>Le GEO consiste à améliorer les informations, les contenus et les signaux qui permettent à ChatGPT, Gemini et Perplexity de comprendre, sélectionner et citer une entreprise.</p><ul>{['Test de visibilité de la marque', 'Cohérence des informations locales', 'Suivi des citations et recommandations de contenus', 'Comparaison avec les concurrents'].map(item => <li key={item}><CheckCircle2 size={17} />{item}</li>)}</ul><button type="button" onClick={onCta} className="nc-pill geo-cta">Tester ma visibilité dans les IA <ArrowRight size={15} /></button></div><div className="geo-panel"><p>Ce que Kompilot observe</p>{['Fiche Google et informations locales', 'Avis et perception client', 'Contenus du site et des réseaux', 'Présence dans les réponses génératives'].map((item, index) => <div key={item}><span>{index + 1}</span><b>{item}</b></div>)}</div></div></section>

    <section id="secteurs" className="landing-section landing-sectors"><div className="landing-container"><div className="landing-section-intro"><p className="nc-section-label">Des pages pensées par métier</p><h2>Une visibilité adaptée à votre activité</h2><p>Chaque secteur dispose de ses enjeux, de ses contenus et de ses signaux locaux.</p></div><div className="sector-grid">{SECTORS.map(([to, title, text]) => <Link key={to} to={to as '/'}><MapPin size={17} /><span><strong>{title}</strong><small>{text}</small></span><ArrowRight size={16} /></Link>)}</div></div></section>

    <section id="temoignages" className="landing-section landing-beta"><div className="landing-container beta-layout"><div><p className="nc-section-label">Bêta en cours</p><h2>Déjà testé par des professionnels locaux.</h2><p>Les premiers retours sont en cours de collecte. Nous publierons uniquement des témoignages attribuables, avec l’accord du professionnel et un résultat vérifiable.</p></div><div className="beta-proof"><FileText size={20} /><div><strong>Pas de chiffres inventés</strong><span>Chaque preuve publiée sera reliée à un cas réel, un secteur et une période.</span></div></div></div></section>
  </>;
}
