import { requireBlinkProjectId } from '../lib/blinkConfig';
import { Hono } from 'hono';
import { createClient } from '@blinkdotnew/sdk';
import type { Env } from '../lib/types';
import { generateAIResponse } from '../lib/aiRouter';
import { fetchCompetitorAdsDetailed } from '../lib/metaAdsService';

export const router = new Hono<{ Bindings: Env }>();
type Row = Record<string, any>;
type ScanStatus = 'queued' | 'running' | 'completed' | 'partial' | 'failed' | 'retryable_failed';
const id = (prefix: string) => `${prefix}_${crypto.randomUUID()}`;
const now = () => new Date().toISOString();
const AXES = [
  ['benefits', 'Bénéfices'], ['proof', 'Preuves'], ['problem', 'Problème ciblé'], ['usp', 'USP'],
  ['pricingOffer', 'Pricing / Offre'], ['productFunctioning', 'Fonctionnement produit'], ['arguments', 'Arguments'], ['brand', 'La marque'],
] as const;

function getBlink(c: any) { return createClient({ projectId: requireBlinkProjectId(c.env), secretKey: c.env.BLINK_SECRET_KEY }); }
async function auth(c: any) {
  const blink = getBlink(c);
  const result = await blink.auth.verifyToken(c.req.header('Authorization'));
  if (!result.valid) return { blink, env: c.env, error: c.json({ error: 'Unauthorized', code: 'UNAUTHORIZED' }, 401) };
  return { blink, env: c.env, userId: result.userId, email: result.email || '' };
}
function bodyOf(c: any) { return c.req.json().catch(() => ({})); }
function normalizePlatform(value: unknown) { return ['meta', 'tiktok', 'linkedin', 'google', 'other'].includes(String(value)) ? String(value) : 'other'; }
function parseJson(value: unknown, fallback: any = {}) { try { return typeof value === 'string' ? JSON.parse(value) : value ?? fallback; } catch { return fallback; } }
function errorMessage(error: unknown) { return error instanceof Error ? error.message : 'Erreur interne du moteur Espion'; }
function sourceStatus(error: unknown) { const msg = errorMessage(error).toLowerCase(); return msg.includes('timeout') ? 'timeout' : msg.includes('401') || msg.includes('unauthorized') ? 'unauthorized' : 'upstream_error'; }
function clamp(value: unknown, fallback = 0) { return Math.max(0, Math.min(100, Number(value) || fallback)); }
function isStale(scan: Row) { return ['queued', 'running', 'retryable_failed'].includes(String(scan.status)) && scan.updatedAt && Date.now() - new Date(scan.updatedAt).getTime() > 10 * 60 * 1000; }

const ESPION_SCORING_VERSION = 'espion_scoring_v1';
const ESPION_PROMPT_VERSION = 'espion_prompt_v2';

async function generateAnalysis(blink: any, userId: string, input: Row, source: Row = {}, env?: Env) {
  const payload = parseJson(input.inputPayload);
  const text = [payload.adText, payload.headline, payload.description, payload.cta, input.adText, input.headline, input.description, input.cta, source.adCreativeBody].filter(Boolean).join('\n');
  const system = `Tu es l'analyste publicitaire senior de Kompilot Espion. Réponds uniquement en JSON valide, sans inventer de preuve. Analyse exactement les 8 axes: ${AXES.map(([, label]) => label).join(', ')}. Pour chaque axe retourne key, label, score 0-100, confidence 0-100, summary, evidence[], recommendations[]. Détecte aussi creativeType (ugc, motion_design, product_demo, before_after, testimonial, carousel, image, video, unknown), copyFramework (AIDA, PAS, Hook-Story-Offer, autre), hook, hookMechanism, offer, audience, cta, description courte de 140 caractères maximum, audioType (human_voice, ai_voice, music, none, unknown), evergreen, maturityScore, strengths[], risks[], recommendations[], iterations[], scalingSignal, saturationSignal. Classe la veille: adActivityStatus (active_ads, no_active_ads, scan_inconclusive), sourceConfidence 0-100, falsePositiveRisk (low, medium, high), falsePositiveReason. Analyse le funnel: landingPagePromise, checkoutType, upsell, funnelFriction[]; le script: transcript, threeSecondHook, proofMoments[]; et les signaux media buyer: winningFormat, iterationSignals[]. Retourne aussi assets[] avec type, url, label, downloadable. Si une information n'est pas visible, retourne 'non détecté' et baisse confidence. Ne transforme jamais un scan incomplet en 'marque sans pub active'.`;
  const prompt = `Plateforme: ${input.platform}\nAnnonceur: ${input.advertiserName || 'non renseigné'}\nNom: ${input.adName || 'non renseigné'}\nURL: ${input.targetUrl || 'non renseignée'}\nPays: ${input.countryCode || 'non renseigné'}\nLocale: ${input.locale || 'non renseignée'}\nSource Ads Library: ${JSON.stringify(source)}\nTexte:\n${text || 'non fourni'}\n\nRetourne cet objet complet: {"axes":[],"creativeType":"unknown","copyFramework":"autre","hook":"","hookMechanism":"","offer":"","audience":"","cta":"","description":"","audioType":"unknown","evergreen":false,"maturityScore":0,"strengths":[],"risks":[],"recommendations":[],"iterations":[],"scalingSignal":"unknown","saturationSignal":"unknown","adActivityStatus":"${source.status || 'scan_inconclusive'}","sourceConfidence":${Number(source.sourceConfidence || 0)},"falsePositiveRisk":"${source.status === 'no_active_ads' ? 'low' : 'high'}","falsePositiveReason":"${source.errorMessage || ''}","winningFormat":"unknown","iterationSignals":[],"landingPagePromise":"","checkoutType":"unknown","upsell":"","funnelFriction":[],"transcript":"","threeSecondHook":"","proofMoments":[],"assets":[]}`;
  const ai = await generateAIResponse({ taskType: 'STRATEGIC_PLANNING', prompt, systemContext: system, forceJson: true, maxTokens: 3800 }, { OPENAI_API_KEY: env?.OPENAI_API_KEY || '', ANTHROPIC_API_KEY: env?.ANTHROPIC_API_KEY || '' }, userId);
  const match = ai.content.match(/\{[\s\S]*\}/);
  if (!match) throw new Error('AI response was not valid JSON');
  const parsed = JSON.parse(match[0]);
  const axes = AXES.map(([key, label]) => {
    const found = Array.isArray(parsed.axes) ? parsed.axes.find((axis: Row) => axis.key === key || axis.label === label) : null;
    return { key, label, score: clamp(found?.score), confidence: clamp(found?.confidence), summary: String(found?.summary || 'Non détecté'), evidence: Array.isArray(found?.evidence) ? found.evidence.slice(0, 5) : [], recommendations: Array.isArray(found?.recommendations) ? found.recommendations.slice(0, 5) : [] };
  });
  const overallScore = Math.round(axes.reduce((sum, axis) => sum + axis.score, 0) / axes.length);
  const description = String(parsed.description || text || 'Description non détectée').slice(0, 140);
  const status = ['active_ads', 'no_active_ads', 'scan_inconclusive'].includes(source.status) ? source.status : 'scan_inconclusive';
  const sourceConfidence = Number(source.sourceConfidence || 0) > 0 ? clamp(source.sourceConfidence) : clamp(parsed.sourceConfidence, Math.min(60, overallScore));
  return { ...parsed, axes, description, adActivityStatus: status, overallScore, maturityScore: clamp(parsed.maturityScore, overallScore), sourceConfidence, analysisConfidence: clamp(axes.reduce((sum, axis) => sum + axis.confidence, 0) / axes.length), falsePositiveRisk: status === 'no_active_ads' ? 'low' : status === 'scan_inconclusive' ? 'high' : parsed.falsePositiveRisk || 'low', falsePositiveReason: source.errorMessage || parsed.falsePositiveReason || '', scoringVersion: ESPION_SCORING_VERSION, promptVersion: ESPION_PROMPT_VERSION, sourceProvider: source.provider || (input.platform === 'meta' ? 'meta_ads_library' : 'unsupported'), sourceErrorCode: source.errorCode || '', generatedAt: now(), provider: ai.provider, usedFallback: ai.usedFallback };
}

async function createAnalysis(blink: any, userId: string, scan: Row, analysis: Row) {
  const table = blink.db.table<Row>('espion_analyses');
  return table.create({ id: id('analysis'), userId, scanId: scan.id, platform: scan.platform, advertiserName: scan.advertiserName, adName: scan.adName, sourceUrl: scan.targetUrl, creativeType: analysis.creativeType || 'unknown', description: analysis.description || '', overallScore: analysis.overallScore || 0, maturityScore: analysis.maturityScore || 0, analysisJson: JSON.stringify(analysis), createdAt: now(), updatedAt: now() });
}

export async function processScan(blink: any, userId: string, scan: Row, metaAccessToken?: string, env?: Env) {
  const scans = blink.db.table<Row>('espion_scans');
  const started = now();
  await scans.update(scan.id, { status: 'running', progress: 20, attemptCount: Number(scan.attemptCount || 0) + 1, startedAt: started, heartbeatAt: started, updatedAt: started });
  try {
    const sourceResult = scan.platform === 'meta'
      ? await fetchCompetitorAdsDetailed(metaAccessToken, scan.advertiserName || scan.adName, 50)
      : { ads: [], status: 'scan_inconclusive', sourceConfidence: 0, errorMessage: 'Source de veille non connectée pour cette plateforme' };
    const sourceAd = sourceResult.ads[0] || {};
    const analysis = await generateAnalysis(blink, userId, scan, { ...sourceResult, adCreativeBody: sourceAd.ad_creative_body, snapshotUrl: sourceAd.ad_snapshot_url, startedAt: sourceAd.ad_delivery_start_time }, env);
    analysis.assets = Array.isArray(analysis.assets) ? analysis.assets : [];
    if (sourceAd.ad_snapshot_url) analysis.assets.push({ type: 'ad_snapshot', url: sourceAd.ad_snapshot_url, label: 'Voir la création source', downloadable: false });
    const saved = await createAnalysis(blink, userId, scan, analysis);
    await scans.update(scan.id, { status: analysis.adActivityStatus === 'scan_inconclusive' ? 'partial' : 'completed', progress: 100, retryable: 0, sourceStatuses: JSON.stringify({ provider: analysis.sourceProvider, status: analysis.adActivityStatus, errorCode: analysis.sourceErrorCode, analysis: 'succeeded', confidence: analysis.sourceConfidence, scoringVersion: ESPION_SCORING_VERSION }), resultJson: JSON.stringify({ analysisId: saved.id, adActivityStatus: analysis.adActivityStatus, scoringVersion: ESPION_SCORING_VERSION }), completedAt: now(), heartbeatAt: now(), updatedAt: now() });
    return saved;
  } catch (error) {
    const attempt = Number(scan.attemptCount || 0) + 1;
    const retryable = attempt < Number(scan.maxAttempts || 3);
    await scans.update(scan.id, { status: retryable ? 'retryable_failed' : 'failed', progress: 0, retryable: retryable ? 1 : 0, errorCode: sourceStatus(error), errorMessage: errorMessage(error).slice(0, 500), nextRetryAt: retryable ? new Date(Date.now() + Math.min(30000, 1000 * (2 ** attempt))).toISOString() : null, heartbeatAt: now(), updatedAt: now() });
    throw error;
  }
}

router.get('/api/espion/scans', async c => { const x = await auth(c); if (x.error) return x.error; const scans = x.blink.db.table<Row>('espion_scans'); const rows = await scans.list({ where: { userId: x.userId }, orderBy: { createdAt: 'desc' }, limit: 50 }); for (const scan of rows) if (isStale(scan)) { await scans.update(scan.id, { status: 'retryable_failed', retryable: 1, errorCode: 'stale_scan_recovered', errorMessage: 'Flux repris automatiquement après expiration du heartbeat', updatedAt: now() }); scan.status = 'retryable_failed'; scan.retryable = 1; scan.errorCode = 'stale_scan_recovered'; } return c.json({ scans: rows }); });
router.post('/api/espion/scans', async c => { const x = await auth(c); if (x.error) return x.error; const b = await bodyOf(c); const scan = await x.blink.db.table<Row>('espion_scans').create({ id: id('scan'), userId: x.userId, platform: normalizePlatform(b.platform), targetUrl: typeof b.targetUrl === 'string' ? b.targetUrl.trim() : '', advertiserName: String(b.advertiserName || ''), adName: String(b.adName || ''), countryCode: String(b.countryCode || ''), locale: String(b.locale || ''), status: 'queued', progress: 0, attemptCount: 0, maxAttempts: 3, retryable: 1, sourceStatuses: '{}', inputPayload: JSON.stringify(b), createdAt: now(), updatedAt: now() }); return c.json({ scanId: scan.id, status: scan.status }, 201); });
router.post('/api/espion/scans/recover', async c => { const x = await auth(c); if (x.error) return x.error; const scans = x.blink.db.table<Row>('espion_scans'); const rows = await scans.list({ where: { userId: x.userId }, orderBy: { updatedAt: 'asc' }, limit: 50 }); const recovered = []; for (const scan of rows) { if (!isStale(scan)) continue; await scans.update(scan.id, { status: 'retryable_failed', retryable: 1, errorCode: 'stale_scan_recovered', errorMessage: 'Scan récupérable après expiration du heartbeat', updatedAt: now() }); recovered.push(scan.id); } return c.json({ recovered, count: recovered.length }); });
router.get('/api/espion/scans/:id', async c => { const x = await auth(c); if (x.error) return x.error; const rows = await x.blink.db.table<Row>('espion_scans').list({ where: { id: c.req.param('id'), userId: x.userId }, limit: 1 }); const scan = rows[0]; if (!scan) return c.json({ error: 'Scan not found' }, 404); const analyses = await x.blink.db.table<Row>('espion_analyses').list({ where: { scanId: scan.id, userId: x.userId }, limit: 1 }); return c.json({ scan, analysis: analyses[0] ? { ...analyses[0], analysis: parseJson(analyses[0].analysisJson) } : null }); });
router.post('/api/espion/scans/:id/process', async c => { const x = await auth(c); if (x.error) return x.error; const rows = await x.blink.db.table<Row>('espion_scans').list({ where: { id: c.req.param('id'), userId: x.userId }, limit: 1 }); const scan = rows[0]; if (!scan) return c.json({ error: 'Scan not found' }, 404); if (scan.status === 'running') return c.json({ status: 'running', scanId: scan.id }, 202); try { const analysis = await processScan(x.blink, x.userId, scan, x.env?.META_ACCESS_TOKEN, x.env); const payload = parseJson(analysis.analysisJson); return c.json({ status: payload.adActivityStatus === 'scan_inconclusive' ? 'partial' : 'completed', analysis: { ...analysis, analysis: payload } }); } catch (error) { return c.json({ status: 'failed', error: errorMessage(error) }, 502); } });
router.post('/api/espion/scans/:id/retry', async c => { const x = await auth(c); if (x.error) return x.error; const scans = x.blink.db.table<Row>('espion_scans'); const rows = await scans.list({ where: { id: c.req.param('id'), userId: x.userId }, limit: 1 }); const scan = rows[0]; if (!scan) return c.json({ error: 'Scan not found' }, 404); if (!['retryable_failed', 'failed', 'partial'].includes(scan.status)) return c.json({ error: 'Scan is not retryable' }, 409); if (Number(scan.attemptCount || 0) >= Number(scan.maxAttempts || 3)) return c.json({ error: 'Maximum retry attempts reached' }, 409); await scans.update(scan.id, { status: 'queued', retryable: 1, errorCode: null, errorMessage: null, nextRetryAt: null, progress: 0, updatedAt: now() }); return c.json({ scanId: scan.id, status: 'queued' }); });

router.get('/api/espion/analyses', async c => { const x = await auth(c); if (x.error) return x.error; const rows = await x.blink.db.table<Row>('espion_analyses').list({ where: { userId: x.userId }, orderBy: { createdAt: 'desc' }, limit: 100 }); return c.json({ analyses: rows.map((row: Row) => ({ ...row, analysis: parseJson(row.analysisJson) })) }); });
router.get('/api/espion/analyses/:id', async c => { const x = await auth(c); if (x.error) return x.error; const rows = await x.blink.db.table<Row>('espion_analyses').list({ where: { id: c.req.param('id'), userId: x.userId }, limit: 1 }); if (!rows[0]) return c.json({ error: 'Analysis not found' }, 404); return c.json({ ...rows[0], analysis: parseJson(rows[0].analysisJson) }); });
router.get('/api/espion/analyses/:id/iterations', async c => { const x = await auth(c); if (x.error) return x.error; const current = (await x.blink.db.table<Row>('espion_analyses').list({ where: { id: c.req.param('id'), userId: x.userId }, limit: 1 }))[0]; if (!current) return c.json({ error: 'Analysis not found' }, 404); const rows = await x.blink.db.table<Row>('espion_analyses').list({ where: { userId: x.userId, advertiserName: current.advertiserName }, orderBy: { createdAt: 'asc' }, limit: 100 }); return c.json({ advertiserName: current.advertiserName, iterations: rows.map((row: Row) => ({ ...row, analysis: parseJson(row.analysisJson) })) }); });

router.get('/api/espion/folders', async c => { const x = await auth(c); if (x.error) return x.error; return c.json({ folders: await x.blink.db.table<Row>('espion_folders').list({ where: { userId: x.userId }, orderBy: { createdAt: 'desc' } }) }); });
router.post('/api/espion/folders', async c => { const x = await auth(c); if (x.error) return x.error; const b = await bodyOf(c); if (!String(b.name || '').trim()) return c.json({ error: 'Folder name required' }, 400); return c.json(await x.blink.db.table<Row>('espion_folders').create({ id: id('folder'), userId: x.userId, name: String(b.name).trim(), description: String(b.description || ''), color: String(b.color || '#0D9488'), createdAt: now(), updatedAt: now() }), 201); });
router.get('/api/espion/swipes', async c => { const x = await auth(c); if (x.error) return x.error; const swipes = await x.blink.db.table<Row>('espion_swipes').list({ where: { userId: x.userId }, orderBy: { createdAt: 'desc' }, limit: 100 }); return c.json({ swipes }); });
router.post('/api/espion/swipes', async c => { const x = await auth(c); if (x.error) return x.error; const b = await bodyOf(c); if (!b.analysisId) return c.json({ error: 'analysisId required' }, 400); const analysis = await x.blink.db.table<Row>('espion_analyses').list({ where: { id: b.analysisId, userId: x.userId }, limit: 1 }); if (!analysis[0]) return c.json({ error: 'Analysis not found' }, 404); return c.json(await x.blink.db.table<Row>('espion_swipes').create({ id: id('swipe'), userId: x.userId, analysisId: b.analysisId, folderId: b.folderId || null, title: String(b.title || analysis[0].adName || 'Ad swipe'), notes: String(b.notes || ''), tags: JSON.stringify(Array.isArray(b.tags) ? b.tags : []), isFavorite: b.isFavorite ? 1 : 0, createdAt: now(), updatedAt: now() }), 201); });
router.patch('/api/espion/swipes/:id', async c => { const x = await auth(c); if (x.error) return x.error; const b = await bodyOf(c); const rows = await x.blink.db.table<Row>('espion_swipes').list({ where: { id: c.req.param('id'), userId: x.userId }, limit: 1 }); if (!rows[0]) return c.json({ error: 'Swipe not found' }, 404); const patch: Row = {}; if (b.title !== undefined) patch.title = String(b.title); if (b.notes !== undefined) patch.notes = String(b.notes); if (b.folderId !== undefined) patch.folderId = b.folderId || null; if (b.tags !== undefined) patch.tags = JSON.stringify(Array.isArray(b.tags) ? b.tags : []); if (b.isFavorite !== undefined) patch.isFavorite = b.isFavorite ? 1 : 0; patch.updatedAt = now(); return c.json(await x.blink.db.table<Row>('espion_swipes').update(rows[0].id, patch)); });
router.delete('/api/espion/swipes/:id', async c => { const x = await auth(c); if (x.error) return x.error; const rows = await x.blink.db.table<Row>('espion_swipes').list({ where: { id: c.req.param('id'), userId: x.userId }, limit: 1 }); if (!rows[0]) return c.json({ error: 'Swipe not found' }, 404); await x.blink.db.table<Row>('espion_swipes').delete(rows[0].id); return c.json({ ok: true }); });

router.get('/api/espion/analyses/:id/comments', async c => { const x = await auth(c); if (x.error) return x.error; const analysisId = c.req.param('id'); const owned = await x.blink.db.table<Row>('espion_analyses').list({ where: { id: analysisId, userId: x.userId }, limit: 1 }); const shared = await x.blink.db.table<Row>('espion_shares').list({ where: { analysisId, sharedWithUserId: x.userId }, limit: 1 }); if (!owned[0] && !shared[0]) return c.json({ error: 'Analysis not found' }, 404); const comments = await x.blink.db.table<Row>('espion_comments').list({ where: { analysisId }, orderBy: { createdAt: 'asc' }, limit: 200 }); return c.json({ comments }); });
router.post('/api/espion/analyses/:id/comments', async c => { const x = await auth(c); if (x.error) return x.error; const b = await bodyOf(c); const analysisId = c.req.param('id'); const owned = await x.blink.db.table<Row>('espion_analyses').list({ where: { id: analysisId, userId: x.userId }, limit: 1 }); const shared = await x.blink.db.table<Row>('espion_shares').list({ where: { analysisId, sharedWithUserId: x.userId }, limit: 1 }); if (!owned[0] && !shared[0]) return c.json({ error: 'Analysis not found' }, 404); const body = String(b.body || '').trim(); if (!body) return c.json({ error: 'Comment body required' }, 400); const comment = await x.blink.db.table<Row>('espion_comments').create({ id: id('comment'), userId: owned[0]?.userId || x.userId, analysisId, authorUserId: x.userId, authorEmail: x.email || x.userId, body, mentions: JSON.stringify(Array.isArray(b.mentions) ? b.mentions : []), createdAt: now(), updatedAt: now() }); return c.json({ comment }, 201); });
router.delete('/api/espion/comments/:id', async c => { const x = await auth(c); if (x.error) return x.error; const rows = await x.blink.db.table<Row>('espion_comments').list({ where: { id: c.req.param('id'), authorUserId: x.userId }, limit: 1 }); if (!rows[0]) return c.json({ error: 'Comment not found' }, 404); await x.blink.db.table<Row>('espion_comments').delete(rows[0].id); return c.json({ ok: true }); });
router.post('/api/espion/analyses/:id/share', async c => { const x = await auth(c); if (x.error) return x.error; const b = await bodyOf(c); const analysisId = c.req.param('id'); const owned = await x.blink.db.table<Row>('espion_analyses').list({ where: { id: analysisId, userId: x.userId }, limit: 1 }); if (!owned[0]) return c.json({ error: 'Only the owner can share an analysis' }, 403); const email = String(b.email || '').trim().toLowerCase(); if (!email) return c.json({ error: 'Team member email required' }, 400); const users = await x.blink.db.table<Row>('users').list({ where: { email }, limit: 1 }); if (!users[0]) return c.json({ error: 'No Kompilot user found with this email' }, 404); const existing = await x.blink.db.table<Row>('espion_shares').list({ where: { analysisId, sharedWithUserId: users[0].id }, limit: 1 }); const share = existing[0] ? await x.blink.db.table<Row>('espion_shares').update(existing[0].id, { sharedWithEmail: email, permission: String(b.permission || 'comment') }) : await x.blink.db.table<Row>('espion_shares').create({ id: id('share'), userId: x.userId, analysisId, sharedWithUserId: users[0].id, sharedWithEmail: email, permission: String(b.permission || 'comment'), createdAt: now() }); return c.json({ share }); });
router.get('/api/espion/analyses/:id/shares', async c => { const x = await auth(c); if (x.error) return x.error; const rows = await x.blink.db.table<Row>('espion_shares').list({ where: { analysisId: c.req.param('id'), userId: x.userId }, orderBy: { createdAt: 'desc' } }); return c.json({ shares: rows }); });
router.get('/api/espion/shared', async c => { const x = await auth(c); if (x.error) return x.error; const shares = await x.blink.db.table<Row>('espion_shares').list({ where: { sharedWithUserId: x.userId }, orderBy: { createdAt: 'desc' }, limit: 100 }); const analyses = []; for (const share of shares) { const rows = await x.blink.db.table<Row>('espion_analyses').list({ where: { id: share.analysisId }, limit: 1 }); if (rows[0]) analyses.push({ ...rows[0], permission: share.permission, analysis: parseJson(rows[0].analysisJson) }); } return c.json({ analyses }); });

router.get('/api/espion/benchmarks', async c => { const x = await auth(c); if (x.error) return x.error; const rows = await x.blink.db.table<Row>('espion_analyses').list({ where: { userId: x.userId }, limit: 100 }); const byPlatform: Row = {}; for (const row of rows) { const key = row.platform || 'other'; byPlatform[key] ??= []; byPlatform[key].push(Number(row.overallScore) || 0); } return c.json({ benchmarks: Object.entries(byPlatform).map(([platform, values]) => { const scores = values as number[]; return { platform, sampleSize: scores.length, averageScore: Math.round(scores.reduce((a, b) => a + b, 0) / scores.length), evergreenRate: Math.round((rows.filter(row => row.platform === platform && parseJson(row.analysisJson).evergreen).length / scores.length) * 100), activeAdsRate: Math.round((rows.filter(row => row.platform === platform && parseJson(row.analysisJson).adActivityStatus === 'active_ads').length / scores.length) * 100) }; }) }); });
router.get('/api/espion/analyses/:id/benchmark', async c => { const x = await auth(c); if (x.error) return x.error; const current = (await x.blink.db.table<Row>('espion_analyses').list({ where: { id: c.req.param('id'), userId: x.userId }, limit: 1 }))[0]; if (!current) return c.json({ error: 'Analysis not found' }, 404); const peers = await x.blink.db.table<Row>('espion_analyses').list({ where: { userId: x.userId, platform: current.platform }, limit: 100 }); const scores = peers.map((peer: Row) => Number(peer.overallScore) || 0).sort((a: number, b: number) => a - b); const below = scores.filter((score: number) => score <= Number(current.overallScore || 0)).length; return c.json({ currentScore: Number(current.overallScore || 0), comparisonCount: scores.length, percentile: scores.length ? Math.round((below / scores.length) * 100) : null, peersAverage: scores.length ? Math.round(scores.reduce((a: number, b: number) => a + b, 0) / scores.length) : null, peerSource: 'bibliothèque Espion', platform: current.platform }); });
router.get('/api/espion/analyses/:id/export', async c => { const x = await auth(c); if (x.error) return x.error; const row = (await x.blink.db.table<Row>('espion_analyses').list({ where: { id: c.req.param('id'), userId: x.userId }, limit: 1 }))[0]; if (!row) return c.json({ error: 'Analysis not found' }, 404); const data = parseJson(row.analysisJson); const values = [row.advertiserName, row.adName, row.platform, row.description, row.overallScore, row.maturityScore, data.creativeType, data.copyFramework, data.hook, data.offer, data.adActivityStatus, data.sourceConfidence, data.scalingSignal, data.saturationSignal].map(value => `"${String(value ?? '').replace(/"/g, '""')}"`); c.header('Content-Type', 'text/csv; charset=utf-8'); c.header('Content-Disposition', `attachment; filename="espion-${row.id}.csv"`); return c.body(`Advertiser,Ad,Platform,Description,Overall score,Maturity,Creative type,Copy framework,Hook,Offer,Ad status,Source confidence,Scaling,Saturation\n${values.join(',')}\n`); });

export default router;