import { Hono } from 'hono';
import { createClient } from '@blinkdotnew/sdk';
import type { Env } from '../lib/types';
import { getPlanEntitlements } from '../../shared/pricingCatalog';

export const router = new Hono<{ Bindings: Env }>();
const roles = ['owner', 'admin', 'editor', 'member', 'guest', 'viewer'];
const get = async (c: any) => { const h = c.req.header('Authorization'); if (!h) return null; const blink = createClient({ projectId: c.env.BLINK_PROJECT_ID, secretKey: c.env.BLINK_SECRET_KEY }); const v = await blink.auth.verifyToken(h); return v.valid ? { id: v.userId, email: v.email, blink } : null; };
const membership = async (u: any, workspaceOwnerId = u.id) => { const rows = await u.blink.db.table<any>('team_members').list({ where: { workspaceOwnerId }, limit: 500 }); return rows.find((m: any) => m.memberUserId === u.id || (m.workspaceOwnerId === u.id && ['owner', 'admin'].includes(m.role))) ?? (workspaceOwnerId === u.id ? { workspaceOwnerId: u.id, memberUserId: u.id, role: 'owner', status: 'active' } : null); };
const canManage = (m: any) => m && ['owner', 'admin'].includes(m.role);
const enforceUserLimit = async (u: any, workspaceOwnerId: string) => {
  const users = await u.blink.db.table<any>('users').list({ where: { id: workspaceOwnerId }, limit: 1 });
  const meta = typeof users[0]?.metadata === 'string' ? JSON.parse(users[0].metadata) : users[0]?.metadata;
  const entitlements = getPlanEntitlements(meta?.plan_id);
  if (!entitlements?.users) throw new Error('Unable to resolve plan user limit');
  const members = await u.blink.db.table<any>('team_members').list({ where: { workspaceOwnerId, status: 'active' }, limit: 500 });
  const invites = await u.blink.db.table<any>('team_invites').list({ where: { workspaceOwnerId, accepted: 0 }, limit: 500 });
  if (1 + members.filter((m: any) => m.memberUserId !== workspaceOwnerId).length + invites.length >= entitlements.users) return false;
  return true;
};
router.get('/api/team', async c => { const u = await get(c); if (!u) return c.json({ error: 'Unauthorized' }, 401); const own = await membership(u); const workspace = own?.workspaceOwnerId || u.id; const rows = await u.blink.db.table<any>('team_members').list({ where: { workspaceOwnerId: workspace }, orderBy: { createdAt: 'asc' } }); if (!rows.some((m: any) => m.memberUserId === u.id)) rows.unshift({ id: `self:${u.id}`, workspaceOwnerId: workspace, memberUserId: u.id, memberEmail: u.email || '', role: 'owner', status: 'active' }); return c.json({ members: rows }); });
router.post('/api/team/invite', async c => { const u = await get(c); if (!u) return c.json({ error: 'Unauthorized' }, 401); const m = await membership(u); if (!canManage(m)) return c.json({ error: 'Owner or admin required' }, 403); let b: any; try { b = await c.req.json(); } catch { return c.json({ error: 'Invalid JSON' }, 400); } const email = String(b.email || '').trim().toLowerCase(); const role = b.role || 'member'; if (!email || !email.includes('@')) return c.json({ error: 'Valid email required' }, 400); if (!roles.includes(role)) return c.json({ error: 'Invalid role' }, 400); if (!await enforceUserLimit(u, m.workspaceOwnerId || u.id)) return c.json({ error: 'Plan user limit reached', code: 'TEAM_LIMIT_REACHED' }, 409); const token = crypto.randomUUID(); const inv = await u.blink.db.table<any>('team_invites').create({ id: crypto.randomUUID(), workspaceOwnerId: m.workspaceOwnerId || u.id, email, role, token, expiresAt: new Date(Date.now() + 7 * 864e5).toISOString(), invitedBy: u.id, accepted: 0 }); const link = `${(c.env as any).APP_URL || 'https://kompilot.fr'}/team/accept-invite?token=${encodeURIComponent(token)}`; try { await u.blink.notifications.email({ to: email, subject: 'Invitation à rejoindre une équipe', text: `Invitation à rejoindre une équipe. Ouvrez ce lien : ${link}`, html: `<p>Invitation à rejoindre une équipe.</p><p><a href="${link}">Accepter l'invitation</a></p>` }); } catch (error: any) { return c.json({ error: 'Invite email failed', message: error?.message || 'Unable to send invite' }, 502); } return c.json({ invite: { id: inv.id, email, role, expiresAt: inv.expiresAt } }, 201); });
router.patch('/api/team/:id/role', async c => { const u = await get(c); if (!u) return c.json({ error: 'Unauthorized' }, 401); const t = u.blink.db.table<any>('team_members'); const x = await t.get(c.req.param('id')); const m = x ? await membership(u, x.workspaceOwnerId) : null; if (!canManage(m)) return c.json({ error: 'Owner or admin required' }, 403); if (!x || x.workspaceOwnerId !== m.workspaceOwnerId) return c.json({ error: 'Not found' }, 404); const b = await c.req.json(); if (!roles.includes(b.role) || (x.role === 'owner' && b.role !== 'owner')) return c.json({ error: 'Invalid role' }, 400); return c.json({ member: await t.update(x.id, { role: b.role }) }); });
router.delete('/api/team/:id', async c => { const u = await get(c); if (!u) return c.json({ error: 'Unauthorized' }, 401); const t = u.blink.db.table<any>('team_members'); const x = await t.get(c.req.param('id')); const m = x ? await membership(u, x.workspaceOwnerId) : null; if (!canManage(m)) return c.json({ error: 'Owner or admin required' }, 403); if (!x || x.workspaceOwnerId !== m.workspaceOwnerId || x.role === 'owner') return c.json({ error: 'Not found' }, 404); await t.delete(x.id); return c.json({ success: true }); });
router.post('/api/team/accept-invite', async c => { const u = await get(c); if (!u) return c.json({ error: 'Unauthorized' }, 401); const b = await c.req.json(); const it = u.blink.db.table<any>('team_invites'); const rows = await it.list({ where: { token: String(b.token || '') }, limit: 1 }); const inv = rows[0]; if (!inv || Number(inv.accepted) === 1 || new Date(inv.expiresAt).getTime() < Date.now()) return c.json({ error: 'Invalid, expired, or already accepted invite' }, 400); if (u.email && inv.email && u.email.toLowerCase() !== inv.email.toLowerCase()) return c.json({ error: 'Invite email does not match signed-in user' }, 403); if (!await enforceUserLimit(u, inv.workspaceOwnerId)) return c.json({ error: 'Plan user limit reached', code: 'TEAM_LIMIT_REACHED' }, 409); const member = await u.blink.db.table<any>('team_members').create({ id: crypto.randomUUID(), workspaceOwnerId: inv.workspaceOwnerId, memberUserId: u.id, memberEmail: inv.email, role: roles.includes(inv.role) ? inv.role : 'member', status: 'active', invitedBy: inv.invitedBy, inviteToken: inv.token }); await it.update(inv.id, { accepted: 1 }); return c.json({ member }); });