-- Agency vertical slice schema. Apply with Blink SQL tooling.
CREATE TABLE IF NOT EXISTS agency_workspaces (id TEXT PRIMARY KEY, name TEXT NOT NULL, owner_id TEXT NOT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS agency_workspace_members (id TEXT PRIMARY KEY, workspace_id TEXT NOT NULL, user_id TEXT NOT NULL, role TEXT NOT NULL CHECK(role IN ('owner','admin','editor','reviewer','viewer')), status TEXT NOT NULL DEFAULT 'active', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(workspace_id,user_id));
CREATE TABLE IF NOT EXISTS agency_assets (id TEXT PRIMARY KEY, workspace_id TEXT NOT NULL, name TEXT NOT NULL, file_url TEXT NOT NULL, file_type TEXT NOT NULL DEFAULT 'other', file_size INTEGER NOT NULL DEFAULT 0, tags TEXT NOT NULL DEFAULT '[]', created_by TEXT NOT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS agency_brand_kits_v2 (id TEXT PRIMARY KEY, workspace_id TEXT NOT NULL, name TEXT NOT NULL, logo_url TEXT NOT NULL DEFAULT '', primary_color TEXT NOT NULL DEFAULT '#0D9488', secondary_color TEXT NOT NULL DEFAULT '#F1F5F9', heading_font TEXT NOT NULL DEFAULT 'DM Sans', body_font TEXT NOT NULL DEFAULT 'DM Sans', created_by TEXT NOT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS agency_content_items (id TEXT PRIMARY KEY, workspace_id TEXT NOT NULL, title TEXT NOT NULL, content_type TEXT NOT NULL DEFAULT 'post', status TEXT NOT NULL DEFAULT 'draft', current_version_id TEXT, created_by TEXT NOT NULL, assigned_to TEXT, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS agency_content_versions (id TEXT PRIMARY KEY, workspace_id TEXT NOT NULL, content_item_id TEXT NOT NULL, version_number INTEGER NOT NULL, body TEXT NOT NULL DEFAULT '', metadata TEXT NOT NULL DEFAULT '{}', created_by TEXT NOT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(content_item_id,version_number));
CREATE TABLE IF NOT EXISTS agency_approvals (id TEXT PRIMARY KEY, workspace_id TEXT NOT NULL, content_item_id TEXT NOT NULL, version_id TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'pending', requested_by TEXT NOT NULL, reviewed_by TEXT, feedback TEXT NOT NULL DEFAULT '', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, reviewed_at DATETIME);
CREATE TABLE IF NOT EXISTS agency_comments (id TEXT PRIMARY KEY, workspace_id TEXT NOT NULL, content_item_id TEXT NOT NULL, version_id TEXT, author_id TEXT NOT NULL, body TEXT NOT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS agency_calendar_events (id TEXT PRIMARY KEY, workspace_id TEXT NOT NULL, content_item_id TEXT, title TEXT NOT NULL, starts_at TEXT NOT NULL, ends_at TEXT, channel TEXT NOT NULL DEFAULT 'general', status TEXT NOT NULL DEFAULT 'planned', created_by TEXT NOT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS idx_agency_members_user ON agency_workspace_members(user_id,workspace_id);
CREATE INDEX IF NOT EXISTS idx_agency_content_workspace ON agency_content_items(workspace_id,status);
CREATE INDEX IF NOT EXISTS idx_agency_assets_workspace ON agency_assets(workspace_id);