import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { blink } from '@/blink/client';
import { BACKEND_URL } from '@/lib/backend';
import type { EspionAnalysis, EspionBenchmark, EspionComment, EspionFolder, EspionScan, EspionShare, EspionSwipe } from '@/lib/espionTypes';

async function request<T>(path: string, init: RequestInit = {}) {
  const token = await blink.auth.getValidToken();
  const response = await fetch(`${BACKEND_URL}${path}`, { ...init, headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}`, ...(init.headers || {}) } });
  const body = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(typeof body?.error === 'string' ? body.error : `Request failed (${response.status})`);
  return body as T;
}

export function useEspionScans() { return useQuery({ queryKey: ['espion', 'scans'], queryFn: () => request<{ scans: EspionScan[] }>('/api/espion/scans'), refetchInterval: 5000 }); }
export function useEspionAnalyses() { return useQuery({ queryKey: ['espion', 'analyses'], queryFn: () => request<{ analyses: EspionAnalysis[] }>('/api/espion/analyses'), refetchInterval: 5000 }); }
export function useEspionFolders() { return useQuery({ queryKey: ['espion', 'folders'], queryFn: () => request<{ folders: EspionFolder[] }>('/api/espion/folders') }); }
export function useEspionSwipes() { return useQuery({ queryKey: ['espion', 'swipes'], queryFn: () => request<{ swipes: EspionSwipe[] }>('/api/espion/swipes') }); }
export function useEspionBenchmark(analysisId: string | undefined) { return useQuery({ queryKey: ['espion', 'benchmark', analysisId], queryFn: () => request<EspionBenchmark>(`/api/espion/analyses/${encodeURIComponent(analysisId!)}/benchmark`), enabled: Boolean(analysisId) }); }
export function useEspionBenchmarks() { return useQuery({ queryKey: ['espion', 'benchmarks'], queryFn: () => request<{ benchmarks: Array<{ platform: string; sampleSize: number; averageScore: number; evergreenRate: number; activeAdsRate: number }> }>('/api/espion/benchmarks') }); }
export function useEspionIterations(analysisId: string | undefined) { return useQuery({ queryKey: ['espion', 'iterations', analysisId], queryFn: () => request<{ advertiserName: string; iterations: EspionAnalysis[] }>(`/api/espion/analyses/${encodeURIComponent(analysisId!)}/iterations`), enabled: Boolean(analysisId) }); }
export function useCreateEspionScan() { const qc = useQueryClient(); return useMutation({ mutationFn: (input: Record<string, unknown>) => request<{ scanId: string; status: string }>('/api/espion/scans', { method: 'POST', body: JSON.stringify(input) }), onSuccess: (created, input) => { qc.setQueryData<{ scans: EspionScan[] }>(['espion', 'scans'], current => ({ scans: [{ id: created.scanId, userId: '', platform: String(input.platform || 'meta'), targetUrl: String(input.targetUrl || ''), advertiserName: String(input.advertiserName || ''), adName: String(input.adName || ''), countryCode: '', locale: '', status: created.status as EspionScan['status'], progress: 0, attemptCount: 0, maxAttempts: 3, retryable: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }, ...(current?.scans ?? [])] })); qc.invalidateQueries({ queryKey: ['espion', 'scans'] }); } }); }
export function useProcessEspionScan() { const qc = useQueryClient(); return useMutation({ mutationFn: (scanId: string) => request<{ status: string; analysis: EspionAnalysis }>(`/api/espion/scans/${encodeURIComponent(scanId)}/process`, { method: 'POST' }), onSuccess: () => { qc.invalidateQueries({ queryKey: ['espion', 'scans'] }); qc.invalidateQueries({ queryKey: ['espion', 'analyses'] }); } }); }
export function useRetryEspionScan() { const qc = useQueryClient(); return useMutation({ mutationFn: (scanId: string) => request<{ scanId: string; status: string }>(`/api/espion/scans/${encodeURIComponent(scanId)}/retry`, { method: 'POST' }), onSuccess: () => qc.invalidateQueries({ queryKey: ['espion', 'scans'] }) }); }
export function useRecoverEspionScans() { const qc = useQueryClient(); return useMutation({ mutationFn: () => request<{ recovered: string[]; count: number }>('/api/espion/scans/recover', { method: 'POST' }), onSuccess: () => qc.invalidateQueries({ queryKey: ['espion', 'scans'] }) }); }
export function useResumeEspionScan() { const qc = useQueryClient(); return useMutation({ mutationFn: async (scan: EspionScan) => { if (scan.status === 'retryable_failed' || scan.status === 'failed' || scan.status === 'partial') await request(`/api/espion/scans/${encodeURIComponent(scan.id)}/retry`, { method: 'POST' }); return request<{ status: string; analysis: EspionAnalysis }>(`/api/espion/scans/${encodeURIComponent(scan.id)}/process`, { method: 'POST' }); }, onSuccess: () => { qc.invalidateQueries({ queryKey: ['espion', 'scans'] }); qc.invalidateQueries({ queryKey: ['espion', 'analyses'] }); } }); }
export function useEspionComments(analysisId: string | undefined) { return useQuery({ queryKey: ['espion', 'comments', analysisId], queryFn: () => request<{ comments: EspionComment[] }>(`/api/espion/analyses/${encodeURIComponent(analysisId!)}/comments`), enabled: Boolean(analysisId) }); }
export function useAddEspionComment(analysisId: string) { const qc = useQueryClient(); return useMutation({ mutationFn: (input: { body: string; mentions?: string[] }) => request<{ comment: EspionComment }>(`/api/espion/analyses/${encodeURIComponent(analysisId)}/comments`, { method: 'POST', body: JSON.stringify(input) }), onSuccess: () => qc.invalidateQueries({ queryKey: ['espion', 'comments', analysisId] }) }); }
export function useDeleteEspionComment(analysisId: string) { const qc = useQueryClient(); return useMutation({ mutationFn: (commentId: string) => request<{ ok: boolean }>(`/api/espion/comments/${encodeURIComponent(commentId)}`, { method: 'DELETE' }), onSuccess: () => qc.invalidateQueries({ queryKey: ['espion', 'comments', analysisId] }) }); }
export function useEspionShares(analysisId: string | undefined) { return useQuery({ queryKey: ['espion', 'shares', analysisId], queryFn: () => request<{ shares: EspionShare[] }>(`/api/espion/analyses/${encodeURIComponent(analysisId!)}/shares`), enabled: Boolean(analysisId) }); }
export function useSharedEspionAnalyses() { return useQuery({ queryKey: ['espion', 'shared'], queryFn: () => request<{ analyses: EspionAnalysis[] }>('/api/espion/shared') }); }
export function useShareEspionAnalysis(analysisId: string) { const qc = useQueryClient(); return useMutation({ mutationFn: (input: { email: string; permission?: string }) => request<{ share: EspionShare }>(`/api/espion/analyses/${encodeURIComponent(analysisId)}/share`, { method: 'POST', body: JSON.stringify(input) }), onSuccess: () => qc.invalidateQueries({ queryKey: ['espion', 'shares', analysisId] }) }); }
export function useCreateEspionFolder() { const qc = useQueryClient(); return useMutation({ mutationFn: (input: { name: string; description?: string }) => request<EspionFolder>('/api/espion/folders', { method: 'POST', body: JSON.stringify(input) }), onSuccess: () => qc.invalidateQueries({ queryKey: ['espion', 'folders'] }) }); }
export function useSaveEspionSwipe() { const qc = useQueryClient(); return useMutation({ mutationFn: (input: Record<string, unknown>) => request<EspionSwipe>('/api/espion/swipes', { method: 'POST', body: JSON.stringify(input) }), onSuccess: () => qc.invalidateQueries({ queryKey: ['espion', 'swipes'] }) }); }
export function useUpdateEspionSwipe() { const qc = useQueryClient(); return useMutation({ mutationFn: ({ id, ...input }: { id: string; [key: string]: unknown }) => request<EspionSwipe>(`/api/espion/swipes/${encodeURIComponent(id)}`, { method: 'PATCH', body: JSON.stringify(input) }), onSuccess: () => qc.invalidateQueries({ queryKey: ['espion', 'swipes'] }) }); }
export function useDeleteEspionSwipe() { const qc = useQueryClient(); return useMutation({ mutationFn: (id: string) => request<{ ok: boolean }>(`/api/espion/swipes/${encodeURIComponent(id)}`, { method: 'DELETE' }), onSuccess: () => qc.invalidateQueries({ queryKey: ['espion', 'swipes'] }) }); }
export async function downloadEspionAnalysisCsv(analysisId: string) { const token = await blink.auth.getValidToken(); const response = await fetch(`${BACKEND_URL}/api/espion/analyses/${encodeURIComponent(analysisId)}/export`, { headers: { Authorization: `Bearer ${token}` } }); if (!response.ok) throw new Error('Impossible d’exporter cette analyse'); const blob = await response.blob(); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = `espion-${analysisId}.csv`; anchor.click(); URL.revokeObjectURL(url); }