import { useState } from 'react';
import { ChevronDown, Check } from 'lucide-react';
import { Button } from '@blinkdotnew/ui';
import { COMPARISON_ROWS, ENTERPRISE_PLAN, PILOT_OFFER, PRICING_SERVICES, getPlansForBilling, type BillingInterval } from '../landing/pricing/PricingData';

export function CommercialOffers({ billing }: { billing: BillingInterval }) {
  const plans = getPlansForBilling(billing);
  const [open, setOpen] = useState<string | null>(null);
  return <div className="mx-auto max-w-6xl px-4 sm:px-6 pb-16">
    <section className="mt-12 rounded-3xl border border-teal-400/20 bg-teal-400/5 p-6 sm:p-8">
      <div className="grid gap-6 lg:grid-cols-[1fr_auto] lg:items-center">
        <div><p className="text-xs font-bold uppercase tracking-[.16em] text-teal-300">Pilote guidé</p><h2 className="mt-2 text-2xl font-bold text-slate-100">30 jours pour lancer Kompilot avec méthode</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-300">{PILOT_OFFER.description} Crédits plafonnés et validation humaine avant toute diffusion.</p><p className="mt-3 text-sm font-semibold text-teal-200">{PILOT_OFFER.note} Aucun renouvellement automatique.</p></div>
        <div className="text-left lg:text-right"><p className="text-3xl font-black text-slate-100">{PILOT_OFFER.priceLabel}</p><p className="mt-1 text-xs text-slate-400">Paiement unique, comptant</p><a href="mailto:sales@kompilot.fr?subject=Pilote%20guidé%20Kompilot" className="mt-4 inline-flex"><Button>Demander le pilote</Button></a></div>
      </div>
      <div className="mt-6 grid gap-2 text-sm text-slate-300 sm:grid-cols-2 lg:grid-cols-3">{['Rendez-vous de lancement', 'Configuration d’un établissement', 'Accès Pro pendant 30 jours', 'Plan d’action initial et onboarding', 'Rendez-vous de bilan', 'Crédits plafonnés + validation humaine'].map(item => <span key={item} className="flex items-start gap-2"><Check className="mt-0.5 h-4 w-4 shrink-0 text-teal-300" />{item}</span>)}</div>
    </section>

    <section className="mt-16"><div className="mb-6"><p className="text-xs font-bold uppercase tracking-[.16em] text-slate-500">Services ponctuels</p><h2 className="mt-2 text-2xl font-bold text-slate-100">Un coup de main quand vous en avez besoin</h2><p className="mt-2 text-sm text-slate-400">Paiement intégral à la commande. Les prestations sur mesure sont précédées d’un devis validé.</p></div><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{PRICING_SERVICES.map(service => <article key={service.id} className="rounded-2xl border border-white/10 bg-white/[.03] p-5"><h3 className="font-semibold text-slate-100">{service.name}</h3><p className="mt-3 text-2xl font-black text-teal-300">{service.priceLabel}</p><p className="mt-3 text-sm leading-6 text-slate-400">{service.description}</p><p className="mt-4 text-xs text-slate-500">{service.paymentRule}</p><a className="mt-5 inline-block text-sm font-semibold text-teal-300 hover:text-teal-200" href={service.id === 'service_custom_quote' ? 'mailto:sales@kompilot.fr?subject=Devis%20service%20Kompilot' : `mailto:sales@kompilot.fr?subject=${encodeURIComponent(service.name)}`}>Nous contacter →</a></article>)}</div></section>

    <section className="mt-16"><h2 className="mb-5 text-2xl font-bold text-slate-100">Comparer les offres</h2><div className="space-y-3 md:hidden">{plans.map(plan => <article key={plan.id} className="rounded-2xl border border-white/10 bg-white/[.03]"><button type="button" className="flex w-full items-center justify-between p-4 text-left font-bold text-slate-100" onClick={() => setOpen(open === plan.id ? null : plan.id)}>{plan.name}<ChevronDown className={`h-4 w-4 transition-transform ${open === plan.id ? 'rotate-180' : ''}`} /></button>{open === plan.id && <div className="space-y-3 border-t border-white/10 p-4 text-sm">{COMPARISON_ROWS.map(row => <div key={row.key} className="flex justify-between gap-4"><span className="text-slate-400">{row.label}</span><span className="text-right text-slate-200">{plan.comparison[row.key]}</span></div>)}</div>}</article>)}</div><div className="hidden overflow-x-auto rounded-2xl border border-white/10 md:block"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-white/[.04] text-slate-200"><tr><th className="p-4">Fonctionnalité</th>{plans.map(plan => <th key={plan.id} className="p-4">{plan.name}</th>)}</tr></thead><tbody>{COMPARISON_ROWS.map(row => <tr key={row.key} className="border-t border-white/10"><th className="p-4 font-normal text-slate-400">{row.label}</th>{plans.map(plan => <td key={plan.id} className="p-4 text-slate-200">{plan.comparison[row.key]}</td>)}</tr>)}</tbody></table></div></section>
    <p className="mt-10 text-center text-xs leading-5 text-slate-500">Prix hors taxes. TVA applicable selon la situation du client. L’essai gratuit de 14 jours est sans carte bancaire. Rien n’envoie, ne publie, ne répond ou n’invite sans validation humaine. Aucun prélèvement n’est effectué sans consentement explicite. Kompilot ne garantit aucun résultat commercial, de référencement ou de visibilité.</p>
  </div>;
}
