import { Link } from '@tanstack/react-router';
import { usePageSeo } from '../hooks/usePageSeo';
import { PUBLIC_ENTITY } from '../config/publicEntity';
import { pageSchema, personSchema, publicGraph } from '../lib/structuredData';
import { PublicPageShell } from '../components/public/PublicPageShell';

export default function AboutPage() {
  const title = 'À propos de Kompilot | Notre mission et notre méthode';
  const description = 'Découvrez la mission de Kompilot, son approche de la visibilité locale, le rôle de l’IA et l’importance de la validation humaine.';
  usePageSeo(title, description, '/a-propos', { structuredData: publicGraph([pageSchema('/a-propos', title, description), { '@type': 'AboutPage', '@id': `${PUBLIC_ENTITY.url}/a-propos#about`, url: `${PUBLIC_ENTITY.url}/a-propos`, name: title, about: { '@id': `${PUBLIC_ENTITY.url}/#organization` } }, personSchema()]) });
  return <PublicPageShell title="Kompilot, le cockpit de visibilité conçu pour les entreprises B2B" eyebrow="À propos"><p className="mt-6 max-w-3xl text-lg leading-8 text-slate-300">Kompilot est un logiciel SaaS B2B de visibilité locale et de communication multicanale. Il aide les PME, commerces, indépendants, multi-établissements et agences à rassembler des actions aujourd’hui dispersées.</p><div className="mt-12 grid gap-6 md:grid-cols-2"><section className="rounded-2xl border border-white/10 bg-white/[.04] p-6"><h2 className="text-2xl font-bold text-white">Pourquoi centraliser ?</h2><p className="mt-4 leading-8 text-slate-300">Quand les contenus, avis, messages, calendriers et données de visibilité sont séparés, les équipes perdent du temps à retrouver le contexte. Kompilot propose un cockpit pour préparer, attribuer et suivre les actions importantes depuis un espace lisible.</p></section><section className="rounded-2xl border border-white/10 bg-white/[.04] p-6"><h2 className="text-2xl font-bold text-white">Le rôle de l’IA</h2><p className="mt-4 leading-8 text-slate-300">L’IA peut aider à résumer, proposer une formulation ou repérer une priorité. Elle ne remplace ni la connaissance de l’entreprise, ni la relecture, ni la décision de publier ou d’envoyer.</p></section><section className="rounded-2xl border border-white/10 bg-white/[.04] p-6"><h2 className="text-2xl font-bold text-white">Une méthode testée avec des bêta-testeurs</h2><p className="mt-4 leading-8 text-slate-300">Les retours de bêta-testeurs servent à améliorer les parcours et les workflows. Ils sont présentés comme des retours d’usage, jamais comme une garantie de performance générale.</p></section><section className="rounded-2xl border border-white/10 bg-white/[.04] p-6"><h2 className="text-2xl font-bold text-white">Une promesse volontairement sobre</h2><p className="mt-4 leading-8 text-slate-300">Kompilot ne promet ni première position, ni citation dans ChatGPT ou Gemini, ni hausse garantie du chiffre d’affaires. Les résultats dépendent des données, des canaux, des actions et du contexte de chaque organisation.</p></section></div><section className="mt-10 rounded-2xl border border-teal-300/20 bg-teal-300/[.06] p-6"><h2 className="text-2xl font-bold text-white">Auteur et contact</h2><p className="mt-3 leading-7 text-slate-300"><strong className="text-white">{PUBLIC_ENTITY.founder.name}</strong>, {PUBLIC_ENTITY.founder.role}. Aucun diplôme, employeur, certification ou profil social n’est ajouté sans information confirmée.</p><p className="mt-3"><a className="text-teal-300 hover:underline" href={`mailto:${PUBLIC_ENTITY.email}`}>{PUBLIC_ENTITY.email}</a></p><Link to="/politique-editoriale" className="mt-5 inline-flex text-teal-300 hover:underline">Lire la politique éditoriale →</Link></section></PublicPageShell>;
}
