import { useEffect, useState } from 'react';
import { Link, useLocation, useNavigate } from '@tanstack/react-router';
import { Bell, Building2, CalendarDays, Check, ChevronRight, FileText, MessageSquare, MoreVertical, RefreshCw, RotateCcw, Settings, ShieldCheck, Star, Users, X } from 'lucide-react';
import { DemoActionModal } from '@/components/demo/DemoActionModal';
import { DemoMobileNav } from '@/components/demo/DemoMobileNav';
import { DemoMoreMenu } from '@/components/demo/DemoMoreMenu';
import { DemoSafetyNotice } from '@/components/demo/DemoSafetyNotice';
import { DemoWorkspaceActions } from '@/components/demo/DemoWorkspaceActions';
import { useDemoData } from '../context/DemoDataProvider';
import { PROFILE_META, type DemoProfile } from '../lib/demoProductData';

const NAV = [
  ['Dashboard', '/demo/workspace'], ['À valider', '/demo/workspace/approvals'], ['Calendrier', '/demo/workspace/calendar'],
  ['Présence locale', '/demo/workspace/presence'], ['Avis', '/demo/workspace/reviews'], ['Studio de contenu', '/demo/workspace/content'],
  ['Messages', '/demo/workspace/messages'], ['Campagnes', '/demo/workspace/campaigns'], ['Résultats', '/demo/workspace/results'],
  ['Clients / établissements', '/demo/workspace/organization'], ['Équipe', '/demo/workspace/team'], ['Paramètres', '/demo/workspace/settings'],
] as const;

function titleForPath(path: string) {
  return NAV.find(([, route]) => route === path)?.[0] ?? 'Dashboard';
}

const cardClass = 'rounded-2xl border border-slate-200 bg-white p-4 shadow-sm';
const actionClass = 'min-h-11 rounded-xl px-3 py-2 text-sm font-bold transition active:scale-95 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-teal-500';

function DemoRouteContent({ path, data, demoData, onAction, onNavigate, onApprovalChange, onReset, onSelectClient, onSelectEstablishment, selectedClientId, selectedEstablishmentId }: {
  path: string;
  data: ReturnType<typeof useDemoData>['data'];
  demoData: ReturnType<typeof useDemoData>['demoData'];
  onAction: (action: string) => void;
  onNavigate: (path: string) => void;
  onApprovalChange: (id: string, status: ReturnType<typeof useDemoData>['data']['approvals'][number]['status']) => void;
  onReset: () => void;
  onSelectClient: (id: string) => void;
  onSelectEstablishment: (id: string) => void;
  selectedClientId: string | null;
  selectedEstablishmentId: string | null;
}) {
  if (path === '/demo/workspace') return <DemoWorkspaceActions data={data} onAction={onAction} onNavigate={onNavigate} onReset={onReset} onApprovalChange={onApprovalChange} />;
  if (path === '/demo/workspace/approvals') return <section className="space-y-3"><p className="text-sm text-slate-500">Une file courte de contenus, avis, messages et campagnes fictifs.</p>{data.approvals.map(item => <article key={item.id} className={`${cardClass} flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between`}><div className="min-w-0"><p className="text-sm font-bold text-slate-900">{item.title}</p><p className="mt-1 text-xs text-slate-500">{item.detail}</p></div><div className="flex items-center gap-2"><select aria-label={`Statut de ${item.title}`} value={item.status} onChange={event => onApprovalChange(item.id, event.target.value as typeof item.status)} className="min-h-11 rounded-xl border border-slate-300 bg-white px-2 text-sm"><option>Brouillon</option><option>À valider</option><option>Validé</option><option>Planifié</option><option>Publié</option></select><button type="button" onClick={() => onAction(item.kind === 'review' ? 'avis' : item.kind === 'message' ? 'message' : item.kind === 'campaign' ? 'campaign' : `post:${item.id}`)} className={`${actionClass} bg-teal-700 text-white`}>Ouvrir</button></div></article>)}</section>;
  if (path === '/demo/workspace/reviews') return <section className="space-y-3">{demoData.reviews.map(review => <button type="button" key={review.id} onClick={() => onAction(`avis:${review.id}`)} className={`${cardClass} block w-full text-left transition hover:border-teal-300 active:scale-[.99]`}><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-bold text-slate-900">{review.author}</p><p className="mt-1 text-amber-600" aria-label={`${review.rating} étoiles`}>{'★'.repeat(review.rating)}<span className="sr-only"> {review.rating} étoiles</span></p></div><span className="rounded-full bg-amber-50 px-2 py-1 text-xs font-bold text-amber-800">{review.replied ? 'Répondu' : 'À traiter'}</span></div><p className="mt-3 line-clamp-3 text-sm leading-6 text-slate-600">{review.text}</p>{review.replyText && <p className="mt-3 rounded-xl bg-emerald-50 p-3 text-xs font-semibold text-emerald-800">Réponse enregistrée : {review.replyText}</p>}<span className="mt-3 block text-xs font-bold text-teal-700">Lire et préparer une réponse <ChevronRight className="inline" size={14} /></span></button>)}</section>;
  if (path === '/demo/workspace/messages') return <section className="space-y-3">{demoData.messages.map(message => <button type="button" key={message.id} onClick={() => onAction(`message:${message.sender}`)} className={`${cardClass} block w-full text-left transition hover:border-teal-300 active:scale-[.99]`}><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-bold text-slate-900">{message.sender}</p><p className="mt-1 text-xs font-semibold text-teal-700">{message.subject}</p></div><MessageSquare size={18} className="shrink-0 text-teal-700" /></div><p className="mt-3 line-clamp-2 text-sm text-slate-600">{message.preview}</p>{message.responseText && <p className="mt-3 rounded-xl bg-emerald-50 p-3 text-xs font-semibold text-emerald-800">Réponse enregistrée : {message.responseText}</p>}<span className="mt-3 block text-xs font-bold text-teal-700">Ouvrir la conversation <ChevronRight className="inline" size={14} /></span></button>)}</section>;
  if (path === '/demo/workspace/content') return <section className="space-y-4"><div className={`${cardClass} border-teal-100 bg-teal-50`}><p className="text-sm font-bold text-teal-900">Créer un contenu fictif</p><p className="mt-1 text-xs text-teal-800">Choisissez un sujet, prévisualisez les canaux, puis validez une planification locale.</p><button type="button" onClick={() => onAction('post')} className={`${actionClass} mt-4 bg-teal-700 text-white`}>Créer un brouillon</button></div>{demoData.publications.map(post => <article key={post.id} className={cardClass}><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="line-clamp-2 text-sm font-bold text-slate-900">{post.title}</p><p className="mt-1 text-xs text-slate-500">{post.channel} · {post.status === 'draft' ? 'Brouillon' : post.status === 'scheduled' ? 'Planifié' : 'Publié'}</p></div><FileText size={18} className="shrink-0 text-violet-600" /></div><button type="button" onClick={() => onAction('post')} className={`${actionClass} mt-4 w-full border border-slate-200 text-slate-700`}>Prévisualiser</button></article>)}</section>;
  if (path === '/demo/workspace/organization') return <section className="space-y-4"><div className={cardClass}><p className="text-sm font-bold text-slate-900">Établissement actif</p><select aria-label="Choisir un établissement" value={selectedEstablishmentId ?? demoData.establishments[0]?.id ?? ''} onChange={event => onSelectEstablishment(event.target.value)} className="mt-3 min-h-11 w-full rounded-xl border border-slate-300 bg-white px-3 text-sm"><option value="" disabled>Choisir un établissement</option>{demoData.establishments.map(establishment => <option key={establishment.id} value={establishment.id}>{establishment.name}</option>)}</select><p className="mt-2 text-xs text-slate-500">{selectedEstablishmentId ? `Établissement actif : ${demoData.establishments.find(item => item.id === selectedEstablishmentId)?.name ?? 'sélection locale'}` : 'Sélection locale uniquement.'}</p></div><div className="grid gap-3 sm:grid-cols-2">{data.clients.map(client => <button type="button" key={client.id} onClick={() => { onSelectClient(client.id); onAction(`client:${client.name}`); }} className={`${cardClass} min-h-28 text-left transition hover:border-teal-300 active:scale-[.99] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-teal-500 ${selectedClientId === client.id ? 'border-teal-500 ring-2 ring-teal-100' : ''}`} aria-pressed={selectedClientId === client.id}><div className="flex items-center justify-between gap-2"><p className="truncate text-sm font-bold text-slate-900">{client.name}</p><Building2 size={17} className="shrink-0 text-teal-700" /></div><p className="mt-1 text-xs text-slate-500">{client.city}</p><p className="mt-4 text-2xl font-black text-teal-700">{client.score}<span className="text-sm font-semibold text-slate-400">/100</span></p><p className="mt-1 text-xs text-slate-500">{client.alert}</p><span className="mt-3 block text-xs font-bold text-teal-700">{selectedClientId === client.id ? 'Client sélectionné' : 'Gérer la fiche'} <ChevronRight className="inline" size={14} /></span></button>)}</div></section>;
  if (path === '/demo/workspace/results') return <section className="space-y-4"><div className="grid grid-cols-2 gap-3">{[['Visibilité locale', `${data.localVisibility}/100`], ['Avis', `${data.rating}/5`], ['Publications', `${data.approvals.filter(item => item.kind === 'post').length}`], ['Leads', `${data.leads}`]].map(([label, value]) => <button type="button" key={label} onClick={() => onAction(`résultat:${label}`)} className={`${cardClass} text-left active:scale-[.98]`}><p className="text-xs font-semibold text-slate-500">{label}</p><p className="mt-2 text-2xl font-black text-slate-900">{value}</p><p className="mt-2 text-xs font-bold text-teal-700">Voir le détail</p></button>)}</div><div className={cardClass}><p className="text-sm font-bold text-slate-900">Résumé de période</p><p className="mt-2 text-sm leading-6 text-slate-600">La visibilité locale progresse dans cette simulation. Les valeurs sont indicatives et ne correspondent à aucun compte connecté.</p></div></section>;
  if (path === '/demo/workspace/team') return <section className="space-y-3">{['Camille · Administratrice', 'Hugo · Éditeur', 'Sofia · Cliente'].map(person => <button type="button" key={person} onClick={() => onAction(`membre:${person}`)} className={`${cardClass} flex w-full items-center justify-between text-left`}><span><strong className="block text-sm text-slate-900">{person.split(' · ')[0]}</strong><span className="text-xs text-slate-500">{person.split(' · ')[1]}</span></span><Users size={18} className="text-teal-700" /></button>)}</section>;
  if (path === '/demo/workspace/settings') return <section className="space-y-3"><div className={cardClass}><div className="flex items-start gap-3"><Settings className="mt-0.5 text-teal-700" size={18} /><div><p className="text-sm font-bold text-slate-900">Préférences de démonstration</p><p className="mt-1 text-xs leading-5 text-slate-500">Toutes les données sont conservées localement dans cette session.</p></div></div><button type="button" onClick={onReset} className={`${actionClass} mt-4 border border-slate-200 text-slate-700`}><RotateCcw className="mr-2 inline" size={15} />Réinitialiser</button></div></section>;
  if (path === '/demo/workspace/presence') return <section className="space-y-3"><div className={`${cardClass} border-teal-100 bg-teal-50`}><div className="flex items-start gap-3"><ShieldCheck className="mt-0.5 text-teal-700" size={20} /><div><p className="text-sm font-bold text-teal-950">Fiche locale simulée</p><p className="mt-1 text-sm leading-6 text-teal-900">Horaires, catégorie et coordonnées de {demoData.company.name} sont prêtes à être vérifiées.</p></div></div><button type="button" onClick={() => onAction('presence')} className={`${actionClass} mt-4 bg-teal-700 text-white`}>Ouvrir la fiche</button></div></section>;
  if (path === '/demo/workspace/calendar') return <section className="space-y-3">{demoData.calendar.map(event => <button type="button" key={event.id} onClick={() => onAction(`calendrier:${event.title}`)} className={`${cardClass} flex w-full items-center gap-3 text-left`}><CalendarDays className="text-violet-600" size={20} /><span className="min-w-0 flex-1"><strong className="block truncate text-sm text-slate-900">{event.title}</strong><span className="text-xs text-slate-500">{event.date} · {event.channel}</span></span><ChevronRight size={16} /></button>)}</section>;
  if (path === '/demo/workspace/campaigns') return <section className="space-y-3"><div className={cardClass}><p className="text-sm font-bold text-slate-900">Campagnes préparées</p><p className="mt-1 text-xs text-slate-500">Les campagnes restent fictives jusqu’à validation.</p><button type="button" onClick={() => onAction('campaign')} className={`${actionClass} mt-4 bg-teal-700 text-white`}>Préparer une campagne</button></div></section>;
  return <section className={cardClass}><p className="text-sm font-bold text-slate-900">État indisponible</p><p className="mt-2 text-sm text-slate-600">Cette section n’est pas disponible dans cette démonstration locale.</p><button type="button" onClick={() => onNavigate('/demo/workspace')} className={`${actionClass} mt-4 bg-teal-700 text-white`}>Revenir au cockpit</button></section>;
}

export default function DemoWorkspacePage() {
  const navigate = useNavigate();
  const location = useLocation();
  const { profile, data, demoData, setProfile, resetDemo, updateApproval, simulateAction, simulateCreatePost, simulateReplyReview, simulateSendMessage, simulateSchedulePost, lastAction, simulateSelectClient, simulateSelectEstablishment, selectedClientId, selectedEstablishmentId } = useDemoData();
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  const [moreOpen, setMoreOpen] = useState(false);
  const [action, setAction] = useState<string | null>(null);
  const [draft, setDraft] = useState('Bonjour, merci pour votre retour. Votre avis nous aide à progresser.');
  const [channels, setChannels] = useState(['Instagram', 'Facebook']);
  const [notificationsOpen, setNotificationsOpen] = useState(false);
  const currentPath = location.pathname;
  const title = titleForPath(currentPath);

  useEffect(() => {
    document.body.style.overflow = mobileMenuOpen || moreOpen || notificationsOpen || Boolean(action) ? 'hidden' : '';
    const onKeyDown = (event: KeyboardEvent) => {
      if (event.key !== 'Escape') return;
      setMobileMenuOpen(false);
      setMoreOpen(false);
      setNotificationsOpen(false);
      if (action) setAction(null);
    };
    window.addEventListener('keydown', onKeyDown);
    return () => { document.body.style.overflow = ''; window.removeEventListener('keydown', onKeyDown); };
  }, [mobileMenuOpen, moreOpen, action, notificationsOpen]);

  const openAction = (nextAction: string) => { setAction(nextAction); const [actionType] = nextAction.split(':', 1); setDraft(actionType === 'avis' ? 'Bonjour, merci pour votre retour. Votre avis nous aide à progresser.' : actionType === 'campaign' ? 'Campagne locale fictive' : ''); setChannels(['Instagram', 'Facebook']); };
  const confirmAction = () => {
    if (!action) return;
    const [actionType, actionTarget] = action.split(':', 2);
    if (actionType === 'avis') simulateReplyReview(actionTarget, draft);
    else if (actionType === 'post') simulateCreatePost(draft || 'Nouveau brouillon fictif', channels);
    else if (actionType === 'message') simulateSendMessage(actionTarget, draft);
    else if (actionType === 'campaign') simulateSchedulePost(draft || 'Campagne fictive');
    else simulateAction(`${actionType} confirmée localement`);
    setAction(null);
  };

  return (
    <div className="min-h-dvh overflow-x-clip bg-slate-50 text-slate-900 pb-[calc(5rem+env(safe-area-inset-bottom))] lg:pb-0">
      <header className="sticky top-0 z-40 flex min-h-16 items-center justify-between gap-3 border-b border-slate-200 bg-white px-3 shadow-sm sm:px-6">
        <div className="flex min-w-0 items-center gap-2"><Link to="/demo" className="shrink-0 text-lg font-black tracking-tight text-teal-700">Kompilot</Link><span className="max-w-[7rem] truncate rounded-full bg-slate-100 px-2 py-1 text-[10px] font-semibold text-slate-700 xs:max-w-[9rem] sm:max-w-[12rem]">{data.establishment}</span><span className="rounded-full bg-amber-100 px-2 py-1 text-[10px] font-bold uppercase tracking-wide text-amber-800">Démo</span></div>
        <div className="flex shrink-0 items-center gap-1"><button type="button" onClick={() => setNotificationsOpen(true)} className="grid min-h-11 min-w-11 place-items-center rounded-xl text-slate-600 hover:bg-slate-100 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-teal-500" aria-label="Notifications"><Bell size={18} /></button><button type="button" onClick={() => setMoreOpen(true)} className="grid min-h-11 min-w-11 place-items-center rounded-xl text-slate-600 hover:bg-slate-100 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-teal-500 lg:hidden" aria-label="Ouvrir le menu contextuel"><MoreVertical size={18} /></button><button type="button" onClick={resetDemo} className="hidden min-h-11 items-center gap-1.5 rounded-xl border border-slate-200 px-3 text-xs font-bold text-slate-600 hover:bg-slate-50 sm:inline-flex"><RotateCcw size={13} /> Réinitialiser</button><Link to="/demo" className={`${actionClass} hidden border border-slate-200 text-slate-700 sm:inline-flex`}>Quitter</Link></div>
      </header>
      {notificationsOpen && <div className="fixed inset-0 z-50 bg-slate-950/35" role="presentation" onClick={() => setNotificationsOpen(false)}><section role="dialog" aria-modal="true" aria-labelledby="demo-notifications-title" className="absolute right-3 top-20 w-[min(22rem,calc(100vw-1.5rem))] rounded-2xl border border-slate-200 bg-white p-4 shadow-2xl" onClick={event => event.stopPropagation()}><div className="flex items-start justify-between gap-3"><div><h2 id="demo-notifications-title" className="text-base font-bold text-slate-950">Notifications</h2><p className="mt-1 text-xs text-slate-500">Activité fictive de cette session.</p></div><button type="button" onClick={() => setNotificationsOpen(false)} aria-label="Fermer les notifications" className="grid min-h-11 min-w-11 place-items-center rounded-xl hover:bg-slate-100 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-teal-500"><X size={18} /></button></div><ul className="mt-3 space-y-2">{data.notifications.map(item => <li key={item} className="rounded-xl bg-slate-50 p-3 text-xs font-semibold text-slate-600">{item}</li>)}</ul></section></div>}
      <div className="mx-auto flex max-w-[1500px]">
        <aside className="hidden w-64 shrink-0 flex-col border-r border-slate-200 bg-white p-4 lg:sticky lg:top-16 lg:flex lg:h-[calc(100dvh-4rem)]">
          <div className="mb-4 rounded-xl border border-teal-100 bg-teal-50 p-3"><p className="text-[10px] font-bold uppercase tracking-wide text-teal-700">Profil sélectionné</p><select aria-label="Choisir un profil" value={profile} onChange={event => setProfile(event.target.value as DemoProfile)} className="mt-2 min-h-11 w-full rounded-xl border border-teal-200 bg-white px-2 text-sm font-semibold focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-teal-500"><option value="commerce">Commerce local</option><option value="artisan">Artisan ou PME</option><option value="agency">Agence</option><option value="network">Multi-établissements</option></select></div>
          <nav aria-label="Navigation de démonstration" className="min-h-0 flex-1 space-y-1 overflow-y-auto">{NAV.map(([label, path]) => <Link key={path} to={path} className={`flex min-h-11 items-center rounded-xl px-3 py-2.5 text-sm font-semibold transition active:scale-[.99] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-teal-500 ${currentPath === path ? 'bg-teal-100 text-teal-800' : 'text-slate-600 hover:bg-slate-100 hover:text-slate-950'}`}>{label}</Link>)}</nav>
          <div className="mt-4 border-t border-slate-200 pt-4"><button type="button" onClick={resetDemo} className="flex min-h-11 w-full items-center gap-2 rounded-xl px-3 text-sm font-semibold text-slate-600 hover:bg-slate-100 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-teal-500"><RefreshCw size={15} /> Réinitialiser la démo</button><button type="button" onClick={() => navigate({ to: '/demo' })} className="mt-1 flex min-h-11 w-full items-center gap-2 rounded-xl px-3 text-sm font-semibold text-slate-600 hover:bg-rose-50 hover:text-rose-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-teal-500"><X size={15} /> Quitter la démo</button></div>
        </aside>
        <main className="min-w-0 flex-1 p-3 sm:p-6 lg:p-8"><div className="mb-4 flex flex-wrap items-center gap-2 text-xs text-slate-500"><span>Démo locale</span><span aria-hidden="true">·</span><span className="max-w-[15rem] truncate">{data.establishment}</span>{lastAction && <span role="status" className="ml-auto max-w-full rounded-full bg-emerald-100 px-2 py-1 font-semibold text-emerald-800">{lastAction}</span>}</div><div className="mb-5"><DemoSafetyNotice /><h1 className="mt-3 text-2xl font-black tracking-tight sm:text-3xl">{title}</h1><p className="mt-1 text-sm text-slate-500">{PROFILE_META[profile].description} Aucun service externe n’est appelé.</p></div><DemoRouteContent path={currentPath} data={data} demoData={demoData} onAction={openAction} onNavigate={path => navigate({ to: path })} onReset={resetDemo} onApprovalChange={updateApproval} onSelectClient={simulateSelectClient} onSelectEstablishment={simulateSelectEstablishment} selectedClientId={selectedClientId} selectedEstablishmentId={selectedEstablishmentId} /><footer className="mt-8 flex flex-wrap items-center justify-between gap-3 border-t border-slate-200 pt-5 text-xs text-slate-500"><span>Mode démo · aucun email, SMS, publication ou paiement réel</span><Link to="/signup" className="font-bold text-teal-700 hover:underline">Demander une démonstration</Link></footer></main>
      </div>
      <DemoMobileNav currentPath={currentPath} onMore={() => setMoreOpen(true)} /><DemoMoreMenu open={moreOpen} onClose={() => setMoreOpen(false)} currentPath={currentPath} onReset={resetDemo} profile={profile} onProfileChange={setProfile} /><DemoActionModal action={action} draft={draft} onDraftChange={setDraft} channels={channels} onChannelsChange={setChannels} clientSummary={action?.startsWith('client:') ? data.clients.find(client => client.name === action.slice(7)) : undefined} onClose={() => setAction(null)} onConfirm={confirmAction} />
    </div>
  );
}
