import { usePageSeo } from '../hooks/usePageSeo';
import { PUBLIC_ENTITY } from '../config/publicEntity';
import { pageSchema } from '../lib/structuredData';
import { PublicPageShell } from '../components/public/PublicPageShell';

export default function EditorialPolicyPage() {
  const title = 'Politique éditoriale | Kompilot';
  const description = 'Comment Kompilot produit, vérifie et met à jour ses contenus publics, avec une assistance IA encadrée et un contact de correction.';
  usePageSeo(title, description, '/politique-editoriale', { structuredData: pageSchema('/politique-editoriale', title, description) });
  return <PublicPageShell title="Une politique éditoriale orientée vers la clarté" eyebrow="Politique éditoriale"><p className="mt-6 max-w-3xl text-lg leading-8 text-slate-300">Cette page décrit les règles suivies pour les contenus publics de Kompilot. Elle complète les informations légales et ne remplace pas les documents contractuels.</p><article className="prose prose-invert mt-12 max-w-3xl prose-headings:text-white prose-p:text-slate-300 prose-p:leading-8"><h2>Qui produit les contenus ?</h2><p>Les contenus sont préparés par l’équipe Kompilot sous la responsabilité de Jérémy Chevrier, fondateur de Kompilot. Les pages sont publiées uniquement lorsque leur périmètre et leurs informations principales sont suffisamment documentés.</p><h2>Comment l’IA peut-elle assister la rédaction ?</h2><p>L’IA peut aider à organiser un plan, reformuler un passage ou proposer une première version. Elle n’est pas utilisée pour inventer des données, des avis, des témoignages, des résultats ou des références.</p><h2>Comment les contenus sont-ils relus ?</h2><p>La relecture vérifie l’exactitude des offres, l’absence de promesse garantie, la cohérence des liens, la lisibilité et la séparation entre démonstration et résultat réel.</p><h2>Comment les sources sont-elles sélectionnées ?</h2><p>Les sources externes doivent être publiques, pertinentes et identifiables. Les recommandations méthodologiques renvoient notamment aux ressources officielles de Google Search Central et de la CNIL lorsque cela est pertinent.</p><h2>Comment les dates sont-elles gérées ?</h2><p>La date de publication correspond à la première mise en ligne du contenu. La date de mise à jour change uniquement lorsqu’une modification substantielle est effectuée, et non à chaque build.</p><h2>Demander une correction</h2><p>Pour signaler une erreur factuelle ou demander une correction, écrivez à <a href={`mailto:${PUBLIC_ENTITY.email}`} className="text-teal-300 hover:underline">{PUBLIC_ENTITY.email}</a> en indiquant l’URL et la source de la correction.</p></article></PublicPageShell>;
}
