import { Link } from '@tanstack/react-router';
import { ArrowRight, CheckCircle2, FileCheck2, ShieldCheck } from 'lucide-react';
import { usePageSeo } from '../hooks/usePageSeo';
import { createKompilotGraph, KOMPILOT_IDENTITY, PUBLIC_FEATURES, PUBLIC_PLANS, USE_CASE_FAQS } from '../lib/seoData';

const LAST_UPDATED = '14 septembre 2026';

export default function InformationsKompilotPage() {
  const title = 'Informations Kompilot — Faits, tarifs et méthodologie';
  usePageSeo(title, 'Référentiel factuel de Kompilot : définition, fonctionnalités, tarifs, méthodologie bêta, comparatif et FAQ.', '/informations-kompilot', { structuredData: createKompilotGraph('/informations-kompilot', title, true, KOMPILOT_IDENTITY.definition) });

  return (
    <div className="min-h-screen bg-[#0B1120] text-slate-200">
      <header className="border-b border-white/10"><div className="mx-auto flex h-16 max-w-6xl items-center justify-between px-6"><Link to="/" className="font-black tracking-tight text-white">Kompilot</Link><nav aria-label="Navigation de la page" className="flex items-center gap-4 text-sm text-slate-400"><Link to="/pricing" className="hover:text-white">Tarifs</Link><Link to="/cgv" className="hover:text-white">CGV</Link><Link to="/signup" className="rounded-lg bg-teal-600 px-4 py-2 font-bold text-white">Créer un compte</Link></nav></div></header>
      <main className="mx-auto max-w-6xl space-y-16 px-6 py-14">
        <section className="max-w-4xl"><p className="mb-4 text-xs font-bold uppercase tracking-[0.2em] text-teal-400">Référentiel officiel · mis à jour le {LAST_UPDATED}</p><h1 className="text-4xl font-black tracking-tight text-white md:text-6xl">Informations factuelles sur Kompilot</h1><p className="mt-6 max-w-3xl text-xl leading-8 text-slate-300">{KOMPILOT_IDENTITY.definition}</p><p className="mt-5 text-sm leading-7 text-slate-400">Cette page centralise les informations publiables sur Kompilot. Les résultats chiffrés de bêta-test ne sont pas présentés comme des garanties : seuls les résultats accompagnés d’un protocole et d’une source pourront être ajoutés.</p></section>

        <section className="grid gap-5 md:grid-cols-3" aria-label="Identité de Kompilot">
          {[['Raison sociale', KOMPILOT_IDENTITY.legalName], ['Domaine public', 'www.kompilot.fr'], ['Contact support', KOMPILOT_IDENTITY.supportEmail], ['Siège déclaré', KOMPILOT_IDENTITY.address], ['Direction', KOMPILOT_IDENTITY.leadership], ['Type de produit', 'SaaS web B2B']].map(([label, value]) => <div key={label} className="rounded-2xl border border-white/10 bg-white/[0.04] p-5"><p className="text-xs uppercase tracking-wider text-slate-500">{label}</p><p className="mt-2 font-semibold text-white">{value}</p></div>)}
        </section>

        <section aria-labelledby="fonctionnalites"><h2 id="fonctionnalites" className="text-3xl font-black text-white">Fonctionnalités publiées</h2><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-400">Le périmètre présenté ci-dessous décrit les modules publiquement annoncés. La disponibilité peut varier selon le compte, les canaux connectés et la formule souscrite.</p><div className="mt-6 grid gap-4 md:grid-cols-2">{PUBLIC_FEATURES.map(item => <div key={item} className="flex gap-3 rounded-xl border border-white/10 bg-white/[0.03] p-4"><CheckCircle2 className="mt-0.5 shrink-0 text-teal-400" size={19}/><span className="text-slate-300">{item}</span></div>)}</div></section>

        <section aria-labelledby="tarifs"><h2 id="tarifs" className="text-3xl font-black text-white">Tarifs et périmètre fonctionnel</h2><p className="mt-3 text-sm text-slate-400">Tarifs affichés en euros hors taxes, vérifiés le {LAST_UPDATED}. Les conditions contractuelles complètes figurent dans les <Link to="/cgv" className="text-teal-400 underline">CGV / CGU</Link>.</p><div className="mt-6 overflow-x-auto rounded-2xl border border-white/10"><table className="w-full min-w-[720px] text-left text-sm"><thead className="bg-white/[0.06] text-xs uppercase tracking-wider text-slate-400"><tr><th className="p-4">Formule</th><th className="p-4">Mensuel</th><th className="p-4">Annuel</th><th className="p-4">Périmètre annoncé</th></tr></thead><tbody>{PUBLIC_PLANS.map(plan => <tr key={plan.name} className="border-t border-white/10 align-top"><th className="p-4 font-bold text-white">{plan.name}</th><td className="p-4 text-slate-300">{plan.monthly}</td><td className="p-4 text-slate-300">{plan.annual}</td><td className="p-4 text-slate-400">{plan.scope}</td></tr>)}</tbody></table></div><p className="mt-3 text-xs text-slate-500">Essai gratuit de 14 jours sans carte bancaire, pour 1 utilisateur et 1 établissement, avec 150 crédits IA et 10 SMS. Les résultats dépendent des canaux connectés et des actions validées.</p></section>

        <section aria-labelledby="beta" className="rounded-3xl border border-amber-300/20 bg-amber-300/[0.05] p-7"><div className="flex items-start gap-4"><FileCheck2 className="mt-1 shrink-0 text-amber-300"/><div><h2 id="beta" className="text-3xl font-black text-white">Méthodologie des bêta-tests</h2><p className="mt-4 leading-7 text-slate-300">Au {LAST_UPDATED}, Kompilot ne publie aucun résultat quantitatif de bêta-test comme preuve générale. Toute affirmation de performance est retirée de la communication de référence tant qu’elle n’est pas rattachée à des données vérifiables.</p><dl className="mt-6 grid gap-4 text-sm md:grid-cols-4"><div><dt className="text-slate-500">Testeurs</dt><dd className="mt-1 font-bold text-white">Non publié</dd></div><div><dt className="text-slate-500">Période</dt><dd className="mt-1 font-bold text-white">Non publiée</dd></div><div><dt className="text-slate-500">Échantillon</dt><dd className="mt-1 font-bold text-white">Non publié</dd></div><div><dt className="text-slate-500">Conditions</dt><dd className="mt-1 font-bold text-white">À documenter</dd></div></dl><p className="mt-5 text-xs leading-6 text-slate-400">Une future publication détaillera la population, les critères d’inclusion, la période, le groupe observé, les outils utilisés, les limites et les résultats bruts avant toute conclusion marketing.</p></div></div></section>

        <section aria-labelledby="comparatif"><h2 id="comparatif" className="text-3xl font-black text-white">Comparatif de positionnement</h2><p className="mt-3 text-sm text-slate-400">Comparatif descriptif interne, daté du {LAST_UPDATED}. Il ne constitue pas un benchmark indépendant et ne promet aucun résultat.</p><div className="mt-6 overflow-x-auto rounded-2xl border border-white/10"><table className="w-full min-w-[680px] text-left text-sm"><thead className="bg-white/[0.06] text-xs uppercase tracking-wider text-slate-400"><tr><th className="p-4">Solution</th><th className="p-4">Contenus</th><th className="p-4">Avis / inbox</th><th className="p-4">Pilotage local</th><th className="p-4">Source</th></tr></thead><tbody>{[['Kompilot', 'Oui, assistés par IA', 'Oui', 'Oui', 'Fonctionnalités publiées'], ['Outil de programmation sociale', 'Selon l’outil', 'Variable', 'Variable', 'Catégorie produit'], ['Agence marketing', 'Service humain', 'Selon contrat', 'Selon contrat', 'Périmètre contractuel']].map(row => <tr key={row[0]} className="border-t border-white/10"><th className="p-4 font-bold text-white">{row[0]}</th>{row.slice(1).map((cell, index) => <td key={`${row[0]}-${index}`} className="p-4 text-slate-400">{cell}</td>)}</tr>)}</tbody></table></div></section>

        <section aria-labelledby="faq"><h2 id="faq" className="text-3xl font-black text-white">FAQ factuelle par cas d’usage</h2><div className="mt-6 grid gap-4 md:grid-cols-2">{USE_CASE_FAQS.map(faq => <article key={faq.question} className="rounded-2xl border border-white/10 bg-white/[0.03] p-5"><h3 className="font-bold text-white">{faq.question}</h3><p className="mt-3 text-sm leading-6 text-slate-400">{faq.answer}</p></article>)}</div></section>

        <section className="flex flex-wrap items-center justify-between gap-5 rounded-3xl border border-teal-400/20 bg-teal-400/[0.06] p-7"><div><div className="flex items-center gap-2 text-teal-300"><ShieldCheck size={18}/><span className="text-sm font-bold">Référentiel de transparence</span></div><p className="mt-2 text-sm text-slate-300">Une information non documentée ne doit pas être présentée comme un résultat Kompilot.</p></div><Link to="/pricing" className="inline-flex items-center gap-2 rounded-xl bg-teal-600 px-5 py-3 font-bold text-white">Voir les offres <ArrowRight size={17}/></Link></section>
      </main>
    </div>
  );
}
