import { Link } from '@tanstack/react-router';
import { ArrowRight, CheckCircle2 } from 'lucide-react';
import { usePageSeo } from '../hooks/usePageSeo';

const PAGES = {
  '/local': { title: 'Marketing local par IA', description: 'Centralisez votre visibilité locale, vos avis Google et vos contenus sociaux avec Kompilot.', heading: 'Pilotez votre marketing local depuis un seul cockpit', intro: 'Kompilot aide les entreprises B2B, commerces et réseaux à gagner en visibilité sans multiplier les outils.', items: ['Suivi et réponses aux avis clients', 'Contenus sociaux adaptés à votre activité', 'Visibilité Google et présence dans les réponses IA'] },
  '/features': { title: 'Fonctionnalités Kompilot', description: 'Découvrez les fonctionnalités de Kompilot pour les contenus, avis, visibilité locale et pilotage multi-établissements.', heading: 'Tout votre marketing opérationnel, réuni', intro: 'De la création de contenus au reporting, Kompilot organise les tâches marketing récurrentes avec une validation humaine.', items: ['Copilote IA et calendrier éditorial', 'Inbox, avis et réputation en ligne', 'Gestion multi-établissements et reporting'] },
  '/temoignages': { title: 'Témoignages clients Kompilot', description: 'Découvrez comment commerçants, artisans et agences utilisent Kompilot au quotidien.', heading: 'Des équipes plus régulières, sans surcharge', intro: 'Les retours bêta servent à améliorer les parcours, les automatismes et la qualité des contenus avant chaque diffusion.', items: ['Cas d’usage commerçants et restaurants', 'Organisation pour artisans et indépendants', 'Pilotage multi-clients pour les agences'] },
  '/faq': { title: 'FAQ Kompilot', description: 'Réponses aux questions fréquentes sur Kompilot, la plateforme IA de marketing local.', heading: 'Questions fréquentes sur Kompilot', intro: 'Kompilot est une plateforme hybride adaptée à l’univers B2B, des indépendants aux réseaux multi-établissements.', items: ['Les contenus importants restent soumis à validation humaine', 'L’essai gratuit permet de découvrir la plateforme', 'Les offres regroupent directement les options annoncées'] },
} as const;

export default function MarketingInfoPage() {
  const path = window.location.pathname as keyof typeof PAGES;
  const page = PAGES[path] ?? PAGES['/features'];
  usePageSeo(`${page.title} | Kompilot`, page.description, path);
  return <div className="min-h-screen bg-[#0B1120] text-slate-200"><header className="border-b border-white/10"><div className="max-w-6xl mx-auto px-6 h-16 flex items-center justify-between"><Link to="/" className="font-extrabold text-xl text-white">Kompilot</Link><Link to="/signup" className="rounded-lg bg-teal-600 px-4 py-2 text-sm font-bold text-white">Essai gratuit</Link></div></header><main><section className="max-w-4xl mx-auto px-6 py-20 text-center"><h1 className="text-4xl md:text-5xl font-black text-white mb-6">{page.heading}</h1><p className="text-xl text-slate-300 mb-10">{page.intro}</p><div className="grid md:grid-cols-3 gap-4 text-left">{page.items.map(item => <div key={item} className="rounded-2xl border border-white/10 bg-white/5 p-5 flex gap-3"><CheckCircle2 className="text-teal-400 shrink-0" size={20}/><span>{item}</span></div>)}</div><div className="mt-12 flex flex-wrap justify-center gap-4"><Link to="/demo" className="rounded-xl border border-white/20 px-6 py-3 font-bold">Voir la démonstration</Link><Link to="/signup" className="rounded-xl bg-teal-600 px-6 py-3 font-bold flex items-center gap-2">Créer mon espace <ArrowRight size={17}/></Link></div></section><section className="max-w-5xl mx-auto px-6 pb-20"><h2 className="text-2xl font-bold text-white mb-5 text-center">Solutions par secteur</h2><nav className="flex flex-wrap justify-center gap-3">{['restaurants','boutiques','beaute','sport','artisans','sante','immobilier','agences'].map(slug => <a key={slug} href={`/secteurs/${slug}`} className="rounded-full border border-white/10 bg-white/5 px-4 py-2 capitalize hover:border-teal-500">{slug}</a>)}</nav></section></main></div>;
}
