import { Link } from '@tanstack/react-router';
import { ArrowRight, CheckCircle2 } from 'lucide-react';
import { usePageSeo } from '../hooks/usePageSeo';
import { createKompilotGraph, KOMPILOT_IDENTITY } from '../lib/seoData';

const PAGES = {
  '/local': { title: 'Marketing local par IA', description: 'Centralisez votre visibilité locale, vos avis Google et vos contenus sociaux avec Kompilot.', heading: 'Pilotez votre marketing local depuis un seul cockpit', intro: 'Kompilot aide les entreprises B2B, commerces et réseaux à gagner en visibilité sans multiplier les outils.', items: ['Suivi et réponses aux avis clients', 'Contenus sociaux adaptés à votre activité', 'Visibilité Google et présence dans les réponses IA'] },
  '/features': { title: 'Fonctionnalités Kompilot', description: 'Découvrez les fonctionnalités de Kompilot pour les contenus, avis, visibilité locale et pilotage multi-établissements.', heading: 'Tout votre marketing opérationnel, réuni', intro: 'De la création de contenus au reporting, Kompilot organise les tâches marketing récurrentes avec une validation humaine.', items: ['Copilote IA et calendrier éditorial', 'Inbox, avis et réputation en ligne', 'Gestion multi-établissements et reporting'] },
  '/temoignages': { title: 'Témoignages clients Kompilot', description: 'Découvrez comment commerçants, artisans et agences utilisent Kompilot au quotidien.', heading: 'Des équipes plus régulières, sans surcharge', intro: 'Les retours bêta servent à améliorer les parcours, les automatismes et la qualité des contenus avant chaque diffusion.', items: ['Cas d’usage commerçants et restaurants', 'Organisation pour artisans et indépendants', 'Pilotage multi-clients pour les agences'] },
  '/faq': { title: 'FAQ Kompilot', description: 'Réponses aux questions fréquentes sur Kompilot, la plateforme IA de marketing local.', heading: 'Questions fréquentes sur Kompilot', intro: 'Kompilot est une plateforme hybride adaptée à l’univers B2B, des indépendants aux réseaux multi-établissements.', items: ['Les contenus importants restent soumis à validation humaine', 'L’essai gratuit permet de découvrir la plateforme', 'Les offres regroupent directement les options annoncées'] },
} as const;

export default function MarketingInfoPage() {
  const path = window.location.pathname as keyof typeof PAGES;
  const page = PAGES[path] ?? PAGES['/features'];
  const pageTitle = `${page.title} | Kompilot`;
  usePageSeo(pageTitle, page.description, path, {
    structuredData: createKompilotGraph(path, page.title, path === '/faq'),
  });

  return <div className="min-h-screen bg-[#0B1120] text-slate-200"><header className="border-b border-white/10"><div className="mx-auto flex h-16 max-w-6xl items-center justify-between px-6"><Link to="/" className="text-xl font-extrabold text-white">Kompilot</Link><nav aria-label="Navigation de la page" className="flex items-center gap-4 text-sm text-slate-400"><Link to="/informations-kompilot" className="hover:text-white">Informations</Link><Link to="/pricing" className="hover:text-white">Tarifs</Link><Link to="/signup" className="rounded-lg bg-teal-600 px-4 py-2 font-bold text-white">Essai gratuit</Link></nav></div></header><main><section className="mx-auto max-w-4xl px-6 py-20 text-center"><p className="mb-4 text-xs font-bold uppercase tracking-[0.2em] text-teal-400">{KOMPILOT_IDENTITY.shortDefinition}</p><h1 className="mb-6 text-4xl font-black text-white md:text-5xl">{page.heading}</h1><p className="mb-10 text-xl text-slate-300">{page.intro}</p><div className="grid gap-4 text-left md:grid-cols-3">{page.items.map(item => <div key={item} className="flex gap-3 rounded-2xl border border-white/10 bg-white/5 p-5"><CheckCircle2 className="shrink-0 text-teal-400" size={20}/><span>{item}</span></div>)}</div><div className="mt-12 flex flex-wrap justify-center gap-4"><Link to="/demo" className="rounded-xl border border-white/20 px-6 py-3 font-bold">Voir la démonstration</Link><Link to="/signup" className="flex items-center gap-2 rounded-xl bg-teal-600 px-6 py-3 font-bold">Créer mon espace <ArrowRight size={17}/></Link></div></section><section className="mx-auto max-w-5xl px-6 pb-20"><h2 className="mb-5 text-center text-2xl font-bold text-white">Solutions par secteur</h2><nav className="flex flex-wrap justify-center gap-3">{['restaurants','boutiques','beaute','sport','artisans','sante','immobilier','agences'].map(slug => <a key={slug} href={`/secteurs/${slug}`} className="rounded-full border border-white/10 bg-white/5 px-4 py-2 capitalize hover:border-teal-500">{slug}</a>)}</nav></section></main></div>;
}
