import { useEffect, type ReactNode } from 'react';
import { AlertCircle, ExternalLink, Globe2, Link2Off, Loader2, RefreshCw, ShieldCheck } from 'lucide-react';
import { Button, Card, CardContent, CardHeader, CardTitle, Badge, toast } from '@blinkdotnew/ui';
import { useAdAccountConnect, useAdAccountDisconnect, useAdAccountsStatus, type AdConnectionStatus } from '../../hooks/useSocialPublish';

function ProviderCard({ provider, label, description, icon, status, onConnect, onDisconnect, loading }: { provider: 'meta' | 'google_ads'; label: string; description: string; icon: ReactNode; status?: AdConnectionStatus; onConnect: () => void; onDisconnect: () => void; loading: boolean }) {
  const connected = Boolean(status?.connected);
  const expired = status?.status === 'token_expired' || status?.status === 'token_error';
  return <div className="rounded-2xl border border-border bg-card p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md">
    <div className="flex items-start gap-3"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-primary/10 text-primary">{icon}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="text-sm font-bold text-foreground">{label}</h3><Badge variant={connected && !expired ? 'default' : expired ? 'secondary' : 'outline'} className="rounded-full text-[10px]">{connected && !expired ? 'Connecté' : expired ? 'Action requise' : 'Non connecté'}</Badge></div><p className="mt-1 text-xs leading-relaxed text-muted-foreground">{description}</p></div></div>
    {expired && <div className="mt-4 flex items-start gap-2 rounded-xl border border-amber-200 bg-amber-50 px-3 py-2 text-xs text-amber-800"><AlertCircle size={14} className="mt-0.5 shrink-0" /><span>{status?.lastError || 'Reconnectez ce compte pour reprendre la synchronisation.'}</span></div>}
    {connected && status?.lastSyncAt && <p className="mt-4 text-[11px] text-muted-foreground">Dernière synchronisation : {new Date(status.lastSyncAt).toLocaleString('fr-FR')}</p>}
    <div className="mt-4 flex flex-wrap gap-2"><Button size="sm" onClick={onConnect} disabled={loading} className="gap-2">{loading ? <Loader2 size={14} className="animate-spin" /> : <ExternalLink size={14} />}{connected ? 'Reconnecter' : `Connecter ${label}`}</Button>{connected && <Button size="sm" variant="outline" onClick={onDisconnect} disabled={loading} className="gap-2"><Link2Off size={14} /> Déconnecter</Button>}</div>
  </div>;
}

export function AdAccountsConnectionPanel() {
  const query = useAdAccountsStatus(); const connect = useAdAccountConnect(); const disconnect = useAdAccountDisconnect();
  useEffect(() => { const params = new URLSearchParams(window.location.search); const status = params.get('ad_status'); const error = params.get('ad_error'); if (status === 'connected') toast.success('Compte publicitaire connecté', { description: 'Les données resteront isolées dans votre organisation.' }); if (status === 'error') toast.error('Connexion impossible', { description: error || 'Réessayez dans quelques instants.' }); if (status) { params.delete('ad_status'); params.delete('ad_error'); window.history.replaceState({}, '', `${window.location.pathname}${params.toString() ? `?${params}` : ''}`); } }, []);
  const action = (provider: 'meta' | 'google_ads') => { connect.mutate(provider, { onError: (error) => toast.error('Connexion impossible', { description: error.message }) }); };
  return <Card><CardHeader><div className="flex items-start gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary/10 text-primary"><ShieldCheck size={18} /></div><div><CardTitle className="text-base">Comptes publicitaires</CardTitle><p className="mt-1 text-xs text-muted-foreground">Connectez vos propres comptes. Kompilot ne partage jamais les jetons entre organisations.</p></div></div></CardHeader><CardContent><div className="grid gap-4 lg:grid-cols-2"><ProviderCard provider="meta" label="Meta Ads" description="Facebook Ads et Instagram Ads, avec vos comptes publicitaires et vos permissions propres." icon={<Globe2 size={19} />} status={query.data?.providers.meta} onConnect={() => action('meta')} onDisconnect={() => disconnect.mutate('meta')} loading={connect.isPending || disconnect.isPending} /><ProviderCard provider="google_ads" label="Google Ads" description="Synchronisez les campagnes Google Ads à partir de votre compte client autorisé." icon={<span className="text-sm font-black">G</span>} status={query.data?.providers.google_ads} onConnect={() => action('google_ads')} onDisconnect={() => disconnect.mutate('google_ads')} loading={connect.isPending || disconnect.isPending} /></div>{query.isLoading && <div className="mt-4 flex items-center gap-2 text-xs text-muted-foreground"><RefreshCw size={13} className="animate-spin" /> Vérification des connexions…</div>}{query.isError && <p className="mt-4 text-xs text-destructive">Impossible de vérifier vos connexions publicitaires. Réessayez.</p>}</CardContent></Card>;
}
